/**
 * C++/CMake generation for the JUCE runtime's `gen` phase. These are the
 * *framework* files a user's project inherits — ephemeral, regenerated on every
 * `gen`, and written under `.soundor/generated/runtimes/juce/`:
 *
 * - `setup.cmake` — the JUCE plumbing (locate JUCE, `juce_add_plugin`, compile
 *   defs, links, generated sources). The user's own `CMakeLists.txt` only
 *   `include()`s this — the single line Soundor injects into a host the user
 *   otherwise fully owns.
 * - `soundor/soundor.h` — umbrella header.
 * - `soundor/SoundorProcessor.{h,cpp}` — the `soundor::AudioProcessor` base:
 *   builds the `AudioProcessorValueTreeState` from the config's parameters,
 *   exposes named raw-parameter pointers, and persists state.
 * - `soundor/SoundorEditor.{h,cpp}` — the `soundor::AudioProcessorEditor` base,
 *   which will host the Soundor UI. Until the native UI lands it is an empty,
 *   fixed-size view.
 * - `soundor/native/SoundorNative.{h,cpp}` — the `soundor:native` interface and
 *   bindings generated from the config's `native` API (see native-codegen.ts).
 *
 * Everything is derived from config only — deterministic, so `gen --check` is
 * reproducible. App-specific behavior lives in the user-owned scaffold.
 */

import { describeNativeApi } from '@soundor/core';
import type { CodegenFile, SoundorConfig } from '@soundor/runtime-sdk';

import { generateNativeModuleSources } from './native-codegen';
import type { JuceFormat, ResolvedJuceOptions } from './options';

type Parameter = SoundorConfig['parameters'][number];

const HEADER = '// This file was generated by Soundor. Do not edit.\n';
const CMAKE_HEADER = '# This file was generated by Soundor. Do not edit.\n';

/** Maps Soundor format ids to JUCE `FORMATS` tokens. */
const FORMAT_TOKENS: Record<JuceFormat, string> = {
  vst3: 'VST3',
  au: 'AU',
  standalone: 'Standalone',
};

export interface GenerateJuceParams {
  readonly options: ResolvedJuceOptions;
  /** Absolute path to the resolved JUCE checkout, when one was found. */
  readonly jucePath?: string | undefined;
}

/** Emits the generated JUCE framework (CMake + `soundor::` base classes). */
export function generateJuceSources(
  config: SoundorConfig,
  params: GenerateJuceParams,
): CodegenFile[] {
  const parameters = [...config.parameters].sort((a, b) =>
    a.id.localeCompare(b.id),
  );
  const nativeApi = describeNativeApi(config.native);
  if (!nativeApi.ok) {
    // Config validation rejects these first; this guards direct callers.
    throw new Error(
      `Invalid native API: ${nativeApi.issues.map((issue) => `${issue.path}: ${issue.message}`).join('; ')}`,
    );
  }
  return [
    { path: 'setup.cmake', contents: renderSetupCmake(params) },
    { path: 'soundor/soundor.h', contents: renderUmbrella() },
    {
      path: 'soundor/SoundorProcessor.h',
      contents: renderProcessorHeader(parameters),
    },
    {
      path: 'soundor/SoundorProcessor.cpp',
      contents: renderProcessorSource(parameters),
    },
    { path: 'soundor/SoundorEditor.h', contents: renderEditorHeader() },
    { path: 'soundor/SoundorEditor.cpp', contents: renderEditorSource() },
    ...generateNativeModuleSources(nativeApi.model),
  ];
}

// ── CMake ──────────────────────────────────────────────────────────────────

function renderSetupCmake(params: GenerateJuceParams): string {
  const { options } = params;
  const formats = options.formats.map((f) => FORMAT_TOKENS[f]).join(' ');
  // Bake the resolved path when known; otherwise leave empty and fall back to
  // the JUCE_DIR cache var / env at configure time. `gen` never requires JUCE.
  const baked = params.jucePath ?? '';
  return `${CMAKE_HEADER}
# JUCE is provided by @soundor/juce-runtime and never downloaded automatically —
# its license requires explicit acceptance. Run 'soundor doctor' to diagnose.
if(NOT DEFINED JUCE_DIR)
  set(JUCE_DIR "${baked}")
endif()
if(NOT JUCE_DIR)
  set(JUCE_DIR "$ENV{JUCE_DIR}")
endif()
if(NOT JUCE_DIR OR NOT EXISTS "\${JUCE_DIR}/CMakeLists.txt")
  message(FATAL_ERROR "JUCE not found. Set jucePath in juceRuntime({ jucePath }) or JUCE_DIR.")
endif()
add_subdirectory("\${JUCE_DIR}" JUCE)

juce_add_plugin(\${PROJECT_NAME}
    VERSION 0.1.0
    COMPANY_NAME ${cmakeString(options.companyName)}
    BUNDLE_ID ${cmakeString(options.bundleId)}
    PLUGIN_MANUFACTURER_CODE ${options.manufacturerCode}
    PLUGIN_CODE ${options.pluginCode}
    FORMATS ${formats}
    PRODUCT_NAME ${cmakeString(options.pluginName)})

target_compile_definitions(\${PROJECT_NAME}
    PUBLIC
        JUCE_USE_CURL=0
        JUCE_WEB_BROWSER=0
        JUCE_VST3_CAN_REPLACE_VST2=0)

target_link_libraries(\${PROJECT_NAME}
    PRIVATE
        juce::juce_audio_utils
    PUBLIC
        juce::juce_recommended_config_flags
        juce::juce_recommended_lto_flags
        juce::juce_recommended_warning_flags)

# Expose the generated headers as <soundor/soundor.h> and compile the base classes.
target_include_directories(\${PROJECT_NAME} PUBLIC \${CMAKE_CURRENT_LIST_DIR})
target_sources(\${PROJECT_NAME}
    PRIVATE
        \${CMAKE_CURRENT_LIST_DIR}/soundor/SoundorProcessor.cpp
        \${CMAKE_CURRENT_LIST_DIR}/soundor/SoundorEditor.cpp)
`;
}

// ── C++ base classes ─────────────────────────────────────────────────────────

function renderUmbrella(): string {
  return `${HEADER}#pragma once\n\n#include "SoundorProcessor.h"\n#include "SoundorEditor.h"\n`;
}

function renderProcessorHeader(parameters: readonly Parameter[]): string {
  const pointers = parameters
    .map(
      (p) =>
        `        std::atomic<float>* ${cppIdent(p.id)}Parameter = nullptr; // "${p.id}"`,
    )
    .join('\n');
  return `${HEADER}#pragma once

#include <juce_audio_processors/juce_audio_processors.h>
#include <atomic>
#include <memory>

namespace soundor
{
    // Base processor: owns the parameter tree generated from soundor.config.
    // Derive your plugin's processor from this and implement the DSP.
    class AudioProcessor : public juce::AudioProcessor
    {
    public:
        AudioProcessor() : AudioProcessor(BusesProperties()) {}
        explicit AudioProcessor(const BusesProperties& ioLayouts);
        ~AudioProcessor() override = default;

        // DO NOT OVERRIDE: parameter state is persisted automatically.
        void getStateInformation(juce::MemoryBlock& destData) override final;
        void setStateInformation(const void* data, int sizeInBytes) override final;

        juce::AudioProcessorValueTreeState& getParameters() { return *parameters; }
        const juce::AudioProcessorValueTreeState& getParameters() const { return *parameters; }

    protected:
        // Named raw-parameter pointers, generated from the config parameters.
${pointers || '        // no parameters'}

    private:
        static juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout();

        std::unique_ptr<juce::AudioProcessorValueTreeState> parameters;

        JUCE_DECLARE_NON_COPYABLE(AudioProcessor)
    };
} // namespace soundor
`;
}

function renderProcessorSource(parameters: readonly Parameter[]): string {
  const assignments = parameters
    .map(
      (p) =>
        `        ${cppIdent(p.id)}Parameter = parameters->getRawParameterValue(${cppString(p.id)});`,
    )
    .join('\n');
  const adds = parameters.map(renderParameterAdd).join('\n');
  return `${HEADER}#include "SoundorProcessor.h"

namespace soundor
{
    AudioProcessor::AudioProcessor(const BusesProperties& ioLayouts)
        : juce::AudioProcessor(ioLayouts)
    {
        parameters = std::make_unique<juce::AudioProcessorValueTreeState>(
            *this, nullptr, "SOUNDOR", createParameterLayout());

${assignments || '        // no parameters'}
    }

    void AudioProcessor::getStateInformation(juce::MemoryBlock& destData)
    {
        if (auto xml = parameters->copyState().createXml())
            copyXmlToBinary(*xml, destData);
    }

    void AudioProcessor::setStateInformation(const void* data, int sizeInBytes)
    {
        if (auto xml = getXmlFromBinary(data, sizeInBytes))
            if (xml->hasTagName(parameters->state.getType()))
                parameters->replaceState(juce::ValueTree::fromXml(*xml));
    }

    juce::AudioProcessorValueTreeState::ParameterLayout AudioProcessor::createParameterLayout()
    {
        juce::AudioProcessorValueTreeState::ParameterLayout layout;
${adds || '        // no parameters'}
        return layout;
    }
} // namespace soundor
`;
}

function renderParameterAdd(parameter: Parameter): string {
  const pid = `juce::ParameterID { ${cppString(parameter.id)}, 1 }`;
  const name = cppString(parameter.label);
  switch (parameter.type) {
    case 'float':
      return `        layout.add(std::make_unique<juce::AudioParameterFloat>(${pid}, ${name}, juce::NormalisableRange<float>(${cppFloat(parameter.min)}, ${cppFloat(parameter.max)}), ${cppFloat(parameter.default)}));`;
    case 'int':
      return `        layout.add(std::make_unique<juce::AudioParameterInt>(${pid}, ${name}, ${cppInt(parameter.min)}, ${cppInt(parameter.max)}, ${cppInt(parameter.default)}));`;
    case 'bool':
      return `        layout.add(std::make_unique<juce::AudioParameterBool>(${pid}, ${name}, ${parameter.default ? 'true' : 'false'}));`;
    case 'enum': {
      const choices = parameter.values.map(cppString).join(', ');
      const index = Math.max(0, parameter.values.indexOf(parameter.default));
      return `        layout.add(std::make_unique<juce::AudioParameterChoice>(${pid}, ${name}, juce::StringArray { ${choices} }, ${index}));`;
    }
  }
}

function renderEditorHeader(): string {
  return `${HEADER}#pragma once

#include <juce_audio_processors/juce_audio_processors.h>

#include "SoundorProcessor.h"

namespace soundor
{
    // Base editor: the plugin view the Soundor UI will render into. Until the
    // native UI lands it is an empty, fixed-size view. Derive your plugin's
    // editor from this.
    class AudioProcessorEditor : public juce::AudioProcessorEditor
    {
    public:
        explicit AudioProcessorEditor(AudioProcessor& owner);
        ~AudioProcessorEditor() override = default;

        void paint(juce::Graphics&) override;

    protected:
        AudioProcessor& processorRef;

    private:
        JUCE_DECLARE_NON_COPYABLE(AudioProcessorEditor)
    };
} // namespace soundor
`;
}

function renderEditorSource(): string {
  return `${HEADER}#include "SoundorEditor.h"

namespace soundor
{
    AudioProcessorEditor::AudioProcessorEditor(AudioProcessor& owner)
        : juce::AudioProcessorEditor(owner), processorRef(owner)
    {
        setSize(800, 600);
    }

    void AudioProcessorEditor::paint(juce::Graphics& g)
    {
        g.fillAll(getLookAndFeel().findColour(juce::ResizableWindow::backgroundColourId));
    }
} // namespace soundor
`;
}

// ── Value helpers ───────────────────────────────────────────────────────────

/** A quoted CMake argument; JSON escaping is a valid subset of CMake's. */
function cmakeString(value: string): string {
  return JSON.stringify(value).replaceAll('$', '\\$');
}

function cppString(value: string): string {
  return JSON.stringify(value);
}

function cppIdent(id: string): string {
  const ident = id.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[0-9]/.test(ident) ? `_${ident}` : ident;
}

function cppFloat(value: number): string {
  return Number.isInteger(value) ? `${value}.0f` : `${value}f`;
}

function cppInt(value: number): string {
  return `${Math.trunc(value)}`;
}
