import type { SoundorConfig } from '@soundor/runtime-sdk';
import { describe, expect, it } from 'vitest';

import { generateJuceSources } from './codegen';
import { resolveJuceOptions } from './options';

const config = {
  plugin: { id: 'com.acme.synth', name: 'Acme $ynth "One"' },
  runtimes: [],
  parameters: [
    {
      type: 'float',
      id: 'gain',
      label: 'Gain',
      min: 0,
      max: 1,
      default: 0.5,
      unit: 'dB',
    },
    { type: 'int', id: 'voices', label: 'Voices', min: 1, max: 8, default: 4 },
    { type: 'bool', id: 'bypass', label: 'Bypass', default: false },
    {
      type: 'enum',
      id: 'mode',
      label: 'Mode',
      values: ['a', 'b', 'c'],
      default: 'b',
    },
  ],
  native: {
    methods: { render: { args: { request: 'string' }, returns: 'number' } },
  },
} as unknown as SoundorConfig;

const options = resolveJuceOptions(
  { formats: ['vst3', 'au'], companyName: 'Acme', pluginCode: 'Syn1' },
  config.plugin,
);

const params = {
  options,
  nativeDir: '/opt/soundor/native',
  abiNamespace: 'p_12345678',
};

function fileMap(cfg: SoundorConfig, jucePath?: string): Map<string, string> {
  return new Map(
    generateJuceSources(cfg, { ...params, jucePath }).map((f) => [
      f.path,
      f.contents,
    ]),
  );
}

describe('generateJuceSources', () => {
  it('emits setup.cmake plus the soundor base classes', () => {
    const paths = generateJuceSources(config, params).map((f) => f.path);
    expect(paths).toEqual([
      'setup.cmake',
      'soundor/soundor.h',
      'soundor/SoundorProcessor.h',
      'soundor/SoundorProcessor.cpp',
      'soundor/SoundorEditor.h',
      'soundor/SoundorEditor.cpp',
      'soundor/native/SoundorNative.h',
      'soundor/native/SoundorNative.cpp',
    ]);
  });

  it('renders setup.cmake with the plugin config and baked JUCE path', () => {
    const setup = fileMap(config, '/opt/JUCE').get('setup.cmake')!;
    // CMake comments use '#', not '//'.
    expect(setup.startsWith('# This file was generated by Soundor')).toBe(true);
    expect(setup).toContain('juce_add_plugin(${PROJECT_NAME}');
    expect(setup).toContain('FORMATS VST3 AU');
    expect(setup).toContain('set(JUCE_DIR "/opt/JUCE")');
    expect(setup).toContain('SoundorProcessor.cpp');
    expect(setup).toContain('JUCE_WEB_BROWSER=0');
    expect(setup).not.toMatch(
      /NEEDS_WEB_BROWSER|NEEDS_WEBVIEW2|SOUNDOR_DEV_URL|SoundorUiData/,
    );
  });

  it("writes the VST3 manifest and signs last, after the project's own steps", () => {
    const setup = fileMap(config).get('setup.cmake')!;
    // JUCE's automatic manifest would land after its own signature.
    expect(setup).toContain('VST3_AUTO_MANIFEST FALSE)');
    expect(setup).toContain(
      'cmake_language(DEFER CALL soundor_finalize_plugin ${PROJECT_NAME})',
    );
  });

  it('takes the plugin identity from the config, quoted for CMake', () => {
    const setup = fileMap(config).get('setup.cmake')!;
    expect(setup).toContain('BUNDLE_ID "com.acme.synth"');
    expect(setup).toContain('PRODUCT_NAME "Acme \\$ynth \\"One\\""');
    expect(setup).toContain('COMPANY_NAME "Acme"');
    expect(setup).toContain('PLUGIN_CODE Syn1');
    expect(setup).toContain(
      `PLUGIN_MANUFACTURER_CODE ${options.manufacturerCode}`,
    );
  });

  it('leaves JUCE_DIR blank when no checkout was resolved', () => {
    const setup = fileMap(config).get('setup.cmake')!;
    expect(setup).toContain('set(JUCE_DIR "")');
  });

  it('builds an APVTS parameter for each type in the processor', () => {
    const proc = fileMap(config).get('soundor/SoundorProcessor.cpp')!;
    expect(proc).toContain(
      'std::make_unique<juce::AudioParameterFloat>(juce::ParameterID { "gain", 1 }, "Gain", juce::NormalisableRange<float>(0.0f, 1.0f), 0.5f)',
    );
    expect(proc).toContain(
      'std::make_unique<juce::AudioParameterInt>(juce::ParameterID { "voices", 1 }, "Voices", 1, 8, 4)',
    );
    expect(proc).toContain(
      'std::make_unique<juce::AudioParameterBool>(juce::ParameterID { "bypass", 1 }, "Bypass", false)',
    );
    expect(proc).toContain(
      'std::make_unique<juce::AudioParameterChoice>(juce::ParameterID { "mode", 1 }, "Mode", juce::StringArray { "a", "b", "c" }, 1)',
    );
  });

  it('exposes a named raw-parameter pointer per parameter', () => {
    const header = fileMap(config).get('soundor/SoundorProcessor.h')!;
    expect(header).toContain('std::atomic<float>* gainParameter = nullptr;');
    const proc = fileMap(config).get('soundor/SoundorProcessor.cpp')!;
    expect(proc).toContain(
      'gainParameter = parameters->getRawParameterValue("gain");',
    );
  });

  it('hosts a JavaScript runtime in the plugin view, without a WebView', () => {
    const editor = [
      fileMap(config).get('soundor/SoundorEditor.h')!,
      fileMap(config).get('soundor/SoundorEditor.cpp')!,
    ].join('\n');
    expect(editor).toContain(
      'class AudioProcessorEditor : public juce::AudioProcessorEditor, private juce::Timer',
    );
    expect(editor).toContain(
      'std::make_shared<backend::JuceParameterHost>(owner.getParameters(), AudioProcessor::parameterInfos())',
    );
    expect(editor).toContain('native::install(context, std::move(api));');
    expect(editor).toContain('        host->tick();');
    expect(editor).not.toMatch(/WebBrowserComponent|__SOUNDOR__|emitEvent/);
  });

  it("sizes the UI surface and forwards the view's input to it", () => {
    const editor = [
      fileMap(config).get('soundor/SoundorEditor.h')!,
      fileMap(config).get('soundor/SoundorEditor.cpp')!,
    ].join('\n');
    expect(editor).toContain('surface.setSize(');
    expect(editor).toContain(
      'deliver(backend::pointerInput(event, ui::PointerInput::Phase::Down));',
    );
    expect(editor).toContain(
      'runtimeHost().surface().wheel(backend::wheelInput(event.position, event.mods, wheel));',
    );
    expect(editor).toContain('handled = surface.text({ text });');
    expect(editor).toContain('setWantsKeyboardFocus(true);');
    // Rendered by the runtime, only when the picture changed, and presented
    // by a compositor that outlives a reloaded runtime.
    expect(editor).toContain('if (runtimeHost().needsRender())');
    expect(editor).toContain('compositor->composite(runtimeHost().frame());');
    // On the GPU where there is one, otherwise on the CPU.
    expect(editor).toContain('render::GpuCompositor::create(');
    expect(editor).toContain(
      'compositor = std::make_unique<render::RasterCompositor>(image);',
    );
    expect(editor).toContain(
      'options.clipboard = std::make_shared<backend::JuceClipboard>();',
    );
    expect(fileMap(config).get('setup.cmake')).toContain(
      'backend/juce/soundor/backend/JuceInput.cpp',
    );
    expect(fileMap(config).get('setup.cmake')).toContain(
      'backend/juce/soundor/backend/JucePresentation.cpp',
    );
  });

  it('builds the Soundor runtime into the plugin under its own ABI namespace', () => {
    const setup = fileMap(config).get('setup.cmake')!;
    expect(setup).toContain('set(SOUNDOR_ABI_NAMESPACE p_12345678)');
    expect(setup).toContain('set(SOUNDOR_BUILD_TESTS OFF)');
    expect(setup).toContain(
      'add_subdirectory("/opt/soundor/native" soundor-runtime)',
    );
    expect(setup).toContain(
      'target_link_libraries(soundor_generated PUBLIC soundor::runtime PRIVATE soundor::runtime_internal)',
    );
    expect(setup).toContain(
      '"/opt/soundor/native/backend/juce/soundor/backend/JuceParameterHost.cpp"',
    );
    expect(setup).toContain(
      'target_link_libraries(${PROJECT_NAME} PRIVATE soundor_generated)',
    );
    for (const file of [
      'soundor/SoundorProcessor.h',
      'soundor/SoundorEditor.h',
    ]) {
      expect(fileMap(config).get(file)).toContain(
        'namespace soundor::inline SOUNDOR_ABI_NAMESPACE',
      );
    }
  });

  it('generates the parameter table soundor:parameters indexes, in APVTS order', () => {
    const proc = fileMap(config).get('soundor/SoundorProcessor.cpp')!;
    const table = proc.slice(proc.indexOf('parameterInfos()'));
    expect(table).toContain(
      '{ "bypass", "Bypass", parameters::Kind::Bool, 0.0, 1.0, 0.0, "", {  } },',
    );
    expect(table).toContain(
      '{ "gain", "Gain", parameters::Kind::Float, 0.0, 1.0, 0.5, "dB", {  } },',
    );
    expect(table).toContain(
      '{ "mode", "Mode", parameters::Kind::Choice, 0.0, 2.0, 1.0, "", { "a", "b", "c" } },',
    );
    expect(table).toContain(
      '{ "voices", "Voices", parameters::Kind::Int, 1.0, 8.0, 4.0, "", {  } },',
    );
    expect(table.indexOf('"bypass"')).toBeLessThan(table.indexOf('"gain"'));
    const header = fileMap(config).get('soundor/SoundorProcessor.h')!;
    expect(header).toContain(
      'virtual std::shared_ptr<native::NativeApi> createNativeApi() { return nullptr; }',
    );
  });

  it('captures the transport in processBlock and hands DSP to process()', () => {
    const header = fileMap(config).get('soundor/SoundorProcessor.h')!;
    expect(header).toContain(
      'virtual void process(juce::AudioBuffer<float>& buffer, juce::MidiBuffer& midi) = 0;',
    );
    expect(header).toContain(
      'void processBlock(juce::AudioBuffer<float>& buffer, juce::MidiBuffer& midi) override final',
    );
    expect(header).toContain('transport.capture(getPlayHead());');
    expect(header).toContain(
      'static constexpr const char* pluginId = "com.acme.synth";',
    );
  });

  it('wires HTTP, host info and the data directory into the runtime', () => {
    const editor = fileMap(config).get('soundor/SoundorEditor.cpp')!;
    expect(editor).toContain(
      'options.http = std::make_shared<backend::JuceHttpClient>();',
    );
    expect(editor).toContain(
      'options.hostInfo = std::make_shared<backend::JuceHostInfo>(owner, owner.transportCapture());',
    );
    expect(editor).toContain('.getChildFile(AudioProcessor::pluginId)');
    const setup = fileMap(config).get('setup.cmake')!;
    for (const name of [
      'JuceHttpClient',
      'JuceParameterHost',
      'JuceTransport',
    ]) {
      expect(setup).toContain(`backend/juce/soundor/backend/${name}.cpp`);
    }
  });

  it('embeds the UI bundle and loads it in the editor', () => {
    const setup = fileMap(config).get('setup.cmake')!;
    expect(setup).toContain('if(SOUNDOR_UI_DIR)');
    expect(setup).toContain(
      'soundor_embed_directory(soundor_generated pluginUi "${SOUNDOR_UI_DIR}")',
    );
    expect(setup).toContain('if(SOUNDOR_UI_DEV_DIR)');
    expect(setup).toContain('SOUNDOR_UI_DEV_DIR_HEX=');
    const editor = fileMap(config).get('soundor/SoundorEditor.cpp')!;
    expect(editor).toContain('#if SOUNDOR_HAS_UI');
    expect(editor).toContain(
      'options.resources = std::make_shared<platform::EmbeddedResources>(embedded::pluginUi());',
    );
    expect(editor).toContain('options.entry = "/bundle.js";');
  });

  it('generates the soundor:native bindings from the native API', () => {
    const header = fileMap(config).get('soundor/native/SoundorNative.h')!;
    expect(header).toContain('virtual double render(std::string request) = 0;');
  });

  it('does not emit app-specific level telemetry (that lives in the scaffold)', () => {
    const all = [...fileMap(config).values()].join('\n');
    expect(all).not.toContain('currentLevel');
    expect(all).not.toContain('audioLevel');
    expect(all).not.toContain('getCurrentLevel');
  });

  it('is deterministic regardless of declaration order', () => {
    const reversed = {
      ...config,
      parameters: [...config.parameters].reverse(),
    } as SoundorConfig;
    expect(generateJuceSources(reversed, params)).toEqual(
      generateJuceSources(config, params),
    );
  });

  it('handles a config with no parameters or native API', () => {
    const empty = {
      plugin: config.plugin,
      runtimes: [],
      parameters: [],
    } as unknown as SoundorConfig;
    const proc = fileMap(empty).get('soundor/SoundorProcessor.cpp')!;
    expect(proc).toContain('// no parameters');
    const native = fileMap(empty).get('soundor/native/SoundorNative.h')!;
    expect(native).toContain('class NativeApi');
  });
});
