import type { SoundorConfig } from '@soundor/runtime-sdk';
import { describe, expect, it } from 'vitest';

import { generateJuceSources } from './codegen';
import { resolveJuceOptions } from './options';

const config = {
  runtimes: [],
  parameters: [
    {
      type: 'float',
      id: 'gain',
      label: 'Gain',
      min: 0,
      max: 1,
      default: 0.5,
      unit: 'dB',
    },
    { type: 'int', id: 'voices', label: 'Voices', min: 1, max: 8, default: 4 },
    { type: 'bool', id: 'bypass', label: 'Bypass', default: false },
    {
      type: 'enum',
      id: 'mode',
      label: 'Mode',
      values: ['a', 'b', 'c'],
      default: 'b',
    },
  ],
  nativeMethods: [{ name: 'render', input: 'Req', output: 'Res' }],
} as unknown as SoundorConfig;

const options = resolveJuceOptions({ plugin: { formats: ['vst3', 'au'] } });

function fileMap(cfg: SoundorConfig, jucePath?: string): Map<string, string> {
  return new Map(
    generateJuceSources(cfg, { options, jucePath }).map((f) => [
      f.path,
      f.contents,
    ]),
  );
}

describe('generateJuceSources', () => {
  it('emits setup.cmake plus the soundor base classes', () => {
    const paths = generateJuceSources(config, { options }).map((f) => f.path);
    expect(paths).toEqual([
      'setup.cmake',
      'soundor/soundor.h',
      'soundor/SoundorProcessor.h',
      'soundor/SoundorProcessor.cpp',
      'soundor/SoundorEditor.h',
      'soundor/SoundorEditor.cpp',
    ]);
  });

  it('renders setup.cmake with the plugin config and baked JUCE path', () => {
    const setup = fileMap(config, '/opt/JUCE').get('setup.cmake')!;
    // CMake comments use '#', not '//'.
    expect(setup.startsWith('# This file was generated by Soundor')).toBe(true);
    expect(setup).toContain('juce_add_plugin(${PROJECT_NAME}');
    expect(setup).toContain('FORMATS VST3 AU');
    expect(setup).toContain('set(JUCE_DIR "/opt/JUCE")');
    expect(setup).toContain('SoundorProcessor.cpp');
  });

  it('leaves JUCE_DIR blank when no checkout was resolved', () => {
    const setup = fileMap(config).get('setup.cmake')!;
    expect(setup).toContain('set(JUCE_DIR "")');
  });

  it('builds an APVTS parameter for each type in the processor', () => {
    const proc = fileMap(config).get('soundor/SoundorProcessor.cpp')!;
    expect(proc).toContain(
      'std::make_unique<juce::AudioParameterFloat>(juce::ParameterID { "gain", 1 }, "Gain", juce::NormalisableRange<float>(0.0f, 1.0f), 0.5f)',
    );
    expect(proc).toContain(
      'std::make_unique<juce::AudioParameterInt>(juce::ParameterID { "voices", 1 }, "Voices", 1, 8, 4)',
    );
    expect(proc).toContain(
      'std::make_unique<juce::AudioParameterBool>(juce::ParameterID { "bypass", 1 }, "Bypass", false)',
    );
    expect(proc).toContain(
      'std::make_unique<juce::AudioParameterChoice>(juce::ParameterID { "mode", 1 }, "Mode", juce::StringArray { "a", "b", "c" }, 1)',
    );
  });

  it('exposes a named raw-parameter pointer per parameter', () => {
    const header = fileMap(config).get('soundor/SoundorProcessor.h')!;
    expect(header).toContain('std::atomic<float>* gainParameter = nullptr;');
    const proc = fileMap(config).get('soundor/SoundorProcessor.cpp')!;
    expect(proc).toContain(
      'gainParameter = parameters->getRawParameterValue("gain");',
    );
  });

  it('enforces a deny-by-default allowlist and injects the manifest in the editor', () => {
    const editor = fileMap(config).get('soundor/SoundorEditor.cpp')!;
    expect(editor).toContain('kAllowedNativeMethods { "render" }');
    expect(editor).toContain('window.__SOUNDOR__');
    expect(editor).toContain('"nativeMethods":["render"]');
    expect(editor).toContain('is not allowlisted');
  });

  it('syncs parameters as a single batched frame', () => {
    const editor = fileMap(config).get('soundor/SoundorEditor.cpp')!;
    expect(editor).toContain('obj->setProperty("type", "params")');
    expect(editor).toContain('obj->setProperty("values", juce::var(values))');
    // Not one message per parameter.
    expect(editor).not.toContain('"type", "param")');
  });

  it('does not emit app-specific level telemetry (that lives in the scaffold)', () => {
    const all = [...fileMap(config).values()].join('\n');
    expect(all).not.toContain('currentLevel');
    expect(all).not.toContain('audioLevel');
    expect(all).not.toContain('getCurrentLevel');
  });

  it('is deterministic regardless of declaration order', () => {
    const reversed = {
      ...config,
      parameters: [...config.parameters].reverse(),
    } as SoundorConfig;
    expect(generateJuceSources(reversed, { options })).toEqual(
      generateJuceSources(config, { options }),
    );
  });

  it('handles a config with no parameters or methods', () => {
    const empty = { runtimes: [], parameters: [] } as unknown as SoundorConfig;
    const proc = fileMap(empty).get('soundor/SoundorProcessor.cpp')!;
    expect(proc).toContain('// no parameters');
    const editor = fileMap(empty).get('soundor/SoundorEditor.cpp')!;
    expect(editor).toContain('kAllowedNativeMethods {  }');
  });
});
