/**
 * C++/CMake generation for the JUCE runtime's `gen` phase. These are the
 * *framework* files a user's project inherits — ephemeral, regenerated on every
 * `gen`, and written under `.soundor/generated/runtimes/juce/`:
 *
 * - `setup.cmake` — the JUCE plumbing (locate JUCE, `juce_add_plugin`, compile
 *   defs, links, generated sources). The user's own `CMakeLists.txt` only
 *   `include()`s this — the single line Soundor injects into a host the user
 *   otherwise fully owns.
 * - `soundor/soundor.h` — umbrella header.
 * - `soundor/SoundorProcessor.{h,cpp}` — the `soundor::AudioProcessor` base:
 *   builds the `AudioProcessorValueTreeState` from the config's parameters,
 *   exposes named raw-parameter pointers, and persists state.
 * - `soundor/SoundorEditor.{h,cpp}` — the `soundor::AudioProcessorEditor` base,
 *   which will host the Soundor UI. Until the native UI lands it is an empty,
 *   fixed-size view.
 * - `soundor/native/SoundorNative.{h,cpp}` — the `soundor:native` interface and
 *   bindings generated from the config's `native` API (see native-codegen.ts).
 *
 * Everything is derived from config only — deterministic, so `gen --check` is
 * reproducible. App-specific behavior lives in the user-owned scaffold.
 */

import { describeNativeApi } from '@soundor/core';
import type { CodegenFile, SoundorConfig } from '@soundor/runtime-sdk';

import { generateNativeModuleSources } from './native-codegen';
import type { JuceFormat, ResolvedJuceOptions } from './options';

type Parameter = SoundorConfig['parameters'][number];

const HEADER = '// This file was generated by Soundor. Do not edit.\n';
/** Generated classes live in the plugin's ABI namespace, like the runtime. */
const NS = 'soundor::inline SOUNDOR_ABI_NAMESPACE';
const CMAKE_HEADER = '# This file was generated by Soundor. Do not edit.\n';

/** Maps Soundor format ids to JUCE `FORMATS` tokens. */
const FORMAT_TOKENS: Record<JuceFormat, string> = {
  vst3: 'VST3',
  au: 'AU',
  standalone: 'Standalone',
};

export interface GenerateJuceParams {
  readonly options: ResolvedJuceOptions;
  /** Absolute path to the resolved JUCE checkout, when one was found. */
  readonly jucePath?: string | undefined;
  /** Absolute path to this package's native runtime sources. */
  readonly nativeDir: string;
  /** The plugin's C++ ABI namespace (derived from `plugin.id`). */
  readonly abiNamespace: string;
}

/** Emits the generated JUCE framework (CMake + `soundor::` base classes). */
export function generateJuceSources(
  config: SoundorConfig,
  params: GenerateJuceParams,
): CodegenFile[] {
  const parameters = [...config.parameters].sort((a, b) =>
    a.id.localeCompare(b.id),
  );
  const nativeApi = describeNativeApi(config.native);
  if (!nativeApi.ok) {
    // Config validation rejects these first; this guards direct callers.
    throw new Error(
      `Invalid native API: ${nativeApi.issues.map((issue) => `${issue.path}: ${issue.message}`).join('; ')}`,
    );
  }
  return [
    { path: 'setup.cmake', contents: renderSetupCmake(params) },
    { path: 'soundor/soundor.h', contents: renderUmbrella() },
    {
      path: 'soundor/SoundorProcessor.h',
      contents: renderProcessorHeader(parameters, config.plugin),
    },
    {
      path: 'soundor/SoundorProcessor.cpp',
      contents: renderProcessorSource(parameters),
    },
    { path: 'soundor/SoundorEditor.h', contents: renderEditorHeader() },
    { path: 'soundor/SoundorEditor.cpp', contents: renderEditorSource() },
    ...generateNativeModuleSources(nativeApi.model),
  ];
}

// ── CMake ──────────────────────────────────────────────────────────────────

function renderSetupCmake(params: GenerateJuceParams): string {
  const { options } = params;
  const formats = options.formats.map((f) => FORMAT_TOKENS[f]).join(' ');
  // Bake the resolved path when known; otherwise leave empty and fall back to
  // the JUCE_DIR cache var / env at configure time. `gen` never requires JUCE.
  const baked = params.jucePath ?? '';
  return `${CMAKE_HEADER}
# JUCE is provided by @soundor/juce-runtime and never downloaded automatically —
# its license requires explicit acceptance. Run 'soundor doctor' to diagnose.
if(NOT DEFINED JUCE_DIR)
  set(JUCE_DIR "${baked}")
endif()
if(NOT JUCE_DIR)
  set(JUCE_DIR "$ENV{JUCE_DIR}")
endif()
if(NOT JUCE_DIR OR NOT EXISTS "\${JUCE_DIR}/CMakeLists.txt")
  message(FATAL_ERROR "JUCE not found. Set jucePath in juceRuntime({ jucePath }) or JUCE_DIR.")
endif()
add_subdirectory("\${JUCE_DIR}" JUCE)

juce_add_plugin(\${PROJECT_NAME}
    VERSION 0.1.0
    COMPANY_NAME ${cmakeString(options.companyName)}
    BUNDLE_ID ${cmakeString(options.bundleId)}
    PLUGIN_MANUFACTURER_CODE ${options.manufacturerCode}
    PLUGIN_CODE ${options.pluginCode}
    FORMATS ${formats}
    PRODUCT_NAME ${cmakeString(options.pluginName)})

target_compile_definitions(\${PROJECT_NAME}
    PUBLIC
        JUCE_USE_CURL=0
        JUCE_WEB_BROWSER=0
        JUCE_VST3_CAN_REPLACE_VST2=0)

target_link_libraries(\${PROJECT_NAME}
    PRIVATE
        juce::juce_audio_utils
    PUBLIC
        juce::juce_recommended_config_flags
        juce::juce_recommended_lto_flags
        juce::juce_recommended_warning_flags)

# The Soundor runtime: QuickJS-NG (fetched and built privately by CMake) and
# the soundor:* modules. Every Soundor C++ symbol is mangled into this plugin's
# own ABI namespace, derived from plugin.id, so Soundor plugins loaded into one
# host never share a symbol.
set(SOUNDOR_ABI_NAMESPACE ${params.abiNamespace})
set(SOUNDOR_BUILD_TESTS OFF)
add_subdirectory(${cmakeString(cmakePath(params.nativeDir))} soundor-runtime)

# Bindings generated from the config's native API.
add_library(soundor_generated STATIC \${CMAKE_CURRENT_LIST_DIR}/soundor/native/SoundorNative.cpp)
target_include_directories(soundor_generated PUBLIC \${CMAKE_CURRENT_LIST_DIR})
target_link_libraries(soundor_generated PUBLIC soundor::runtime PRIVATE soundor::runtime_internal)
soundor_configure_target(soundor_generated)

# Expose the generated headers as <soundor/soundor.h> and compile the base
# classes together with the JUCE adapters.
target_include_directories(\${PROJECT_NAME}
    PUBLIC
        \${CMAKE_CURRENT_LIST_DIR}
        ${cmakeString(cmakePath(`${params.nativeDir}/backend/juce`))})
target_sources(\${PROJECT_NAME}
    PRIVATE
        \${CMAKE_CURRENT_LIST_DIR}/soundor/SoundorProcessor.cpp
        \${CMAKE_CURRENT_LIST_DIR}/soundor/SoundorEditor.cpp
        ${['JuceHttpClient', 'JuceInput', 'JuceParameterHost', 'JuceTransport']
          .map((name) =>
            cmakeString(
              cmakePath(
                `${params.nativeDir}/backend/juce/soundor/backend/${name}.cpp`,
              ),
            ),
          )
          .join('\n        ')})
target_link_libraries(\${PROJECT_NAME} PRIVATE soundor_generated)

# The plugin UI bundle the CLI built (soundor dev / soundor build), compiled
# into the plugin so it needs no files at runtime.
if(SOUNDOR_UI_DIR)
  soundor_embed_directory(soundor_generated pluginUi "\${SOUNDOR_UI_DIR}")
  target_compile_definitions(\${PROJECT_NAME} PRIVATE SOUNDOR_HAS_UI=1)
endif()

# soundor dev: the plugin loads the UI from the directory the CLI keeps
# rebuilding, reloads it on every build, and logs to a file the CLI shows.
# The paths travel hex-encoded UTF-8, safe from any escaping or code page.
if(SOUNDOR_UI_DEV_DIR)
  file(TO_CMAKE_PATH "\${SOUNDOR_UI_DEV_DIR}" soundor_ui_dev_dir)
  file(TO_CMAKE_PATH "\${SOUNDOR_UI_DEV_LOG}" soundor_ui_dev_log)
  string(HEX "\${soundor_ui_dev_dir}" soundor_ui_dev_dir)
  string(HEX "\${soundor_ui_dev_log}" soundor_ui_dev_log)
  target_compile_definitions(\${PROJECT_NAME}
      PRIVATE
          SOUNDOR_UI_DEV=1
          SOUNDOR_UI_DEV_DIR_HEX="\${soundor_ui_dev_dir}"
          SOUNDOR_UI_DEV_LOG_HEX="\${soundor_ui_dev_log}")
endif()
`;
}

// ── C++ base classes ─────────────────────────────────────────────────────────

function renderUmbrella(): string {
  return `${HEADER}#pragma once\n\n#include "SoundorProcessor.h"\n#include "SoundorEditor.h"\n`;
}

function renderProcessorHeader(
  parameters: readonly Parameter[],
  plugin: SoundorConfig['plugin'],
): string {
  const pointers = parameters
    .map(
      (p) =>
        `        std::atomic<float>* ${cppIdent(p.id)}Parameter = nullptr; // "${p.id}"`,
    )
    .join('\n');
  return `${HEADER}#pragma once

#include <juce_audio_processors/juce_audio_processors.h>
#include <soundor/backend/JuceTransport.h>
#include <soundor/native/SoundorNative.h>
#include <soundor/parameters/Parameters.h>

#include <atomic>
#include <memory>
#include <span>

namespace ${NS}
{
    // Base processor: owns the parameter tree generated from soundor.config.
    // Derive your plugin's processor from this and implement the DSP.
    class AudioProcessor : public juce::AudioProcessor
    {
    public:
        AudioProcessor() : AudioProcessor(BusesProperties()) {}
        explicit AudioProcessor(const BusesProperties& ioLayouts);
        ~AudioProcessor() override = default;

        // The plugin's identity (soundor.config \`plugin\`).
        static constexpr const char* pluginId = ${cppString(plugin.id)};
        static constexpr const char* pluginName = ${cppString(plugin.name)};

        // DO NOT OVERRIDE: parameter state is persisted automatically.
        void getStateInformation(juce::MemoryBlock& destData) override final;
        void setStateInformation(const void* data, int sizeInBytes) override final;

        // Implement your DSP here. Called on the audio thread for every block,
        // like juce::AudioProcessor::processBlock (which Soundor implements to
        // capture the host's transport for soundor:host first).
        virtual void process(juce::AudioBuffer<float>& buffer, juce::MidiBuffer& midi) = 0;

        void processBlock(juce::AudioBuffer<float>& buffer, juce::MidiBuffer& midi) override final
        {
            transport.capture(getPlayHead());
            process(buffer, midi);
        }
        using juce::AudioProcessor::processBlock;

        // The transport captured from the audio thread (read by soundor:host).
        const backend::TransportCapture& transportCapture() const noexcept { return transport; }

        juce::AudioProcessorValueTreeState& getParameters() { return *parameters; }
        const juce::AudioProcessorValueTreeState& getParameters() const { return *parameters; }

        // The config's parameters, in the order soundor:parameters indexes them.
        static std::span<const parameters::Info> parameterInfos();

        // Override to implement the config's native API (soundor:native). Called
        // on the message thread for every new UI runtime; return nullptr when
        // the plugin declares no native methods.
        virtual std::shared_ptr<native::NativeApi> createNativeApi() { return nullptr; }

    protected:
        // Named raw-parameter pointers, generated from the config parameters.
${pointers || '        // no parameters'}

    private:
        static juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout();

        std::unique_ptr<juce::AudioProcessorValueTreeState> parameters;
        backend::TransportCapture transport;

        JUCE_DECLARE_NON_COPYABLE(AudioProcessor)
    };
} // namespace ${NS}
`;
}

function renderProcessorSource(parameters: readonly Parameter[]): string {
  const assignments = parameters
    .map(
      (p) =>
        `        ${cppIdent(p.id)}Parameter = parameters->getRawParameterValue(${cppString(p.id)});`,
    )
    .join('\n');
  const adds = parameters.map(renderParameterAdd).join('\n');
  const infos = parameters.map(renderParameterInfo).join('\n');
  return `${HEADER}#include "SoundorProcessor.h"

namespace ${NS}
{
    AudioProcessor::AudioProcessor(const BusesProperties& ioLayouts)
        : juce::AudioProcessor(ioLayouts)
    {
        parameters = std::make_unique<juce::AudioProcessorValueTreeState>(
            *this, nullptr, "SOUNDOR", createParameterLayout());

${assignments || '        // no parameters'}
    }

    void AudioProcessor::getStateInformation(juce::MemoryBlock& destData)
    {
        if (auto xml = parameters->copyState().createXml())
            copyXmlToBinary(*xml, destData);
    }

    void AudioProcessor::setStateInformation(const void* data, int sizeInBytes)
    {
        if (auto xml = getXmlFromBinary(data, sizeInBytes))
            if (xml->hasTagName(parameters->state.getType()))
                parameters->replaceState(juce::ValueTree::fromXml(*xml));
    }

    juce::AudioProcessorValueTreeState::ParameterLayout AudioProcessor::createParameterLayout()
    {
        juce::AudioProcessorValueTreeState::ParameterLayout layout;
${adds || '        // no parameters'}
        return layout;
    }

    std::span<const parameters::Info> AudioProcessor::parameterInfos()
    {
        static const std::vector<parameters::Info> infos {
${infos || '            // no parameters'}
        };
        return infos;
    }
} // namespace ${NS}
`;
}

function renderParameterInfo(parameter: Parameter): string {
  const fields = (
    kind: string,
    min: number,
    max: number,
    value: number,
    unit = '',
    choices: readonly string[] = [],
  ) =>
    `            { ${cppString(parameter.id)}, ${cppString(parameter.label)}, parameters::Kind::${kind}, ${cppDouble(min)}, ${cppDouble(max)}, ${cppDouble(value)}, ${cppString(unit)}, { ${choices.map(cppString).join(', ')} } },`;
  switch (parameter.type) {
    case 'float':
      return fields(
        'Float',
        parameter.min,
        parameter.max,
        parameter.default,
        parameter.unit,
      );
    case 'int':
      return fields(
        'Int',
        parameter.min,
        parameter.max,
        parameter.default,
        parameter.unit,
      );
    case 'bool':
      return fields('Bool', 0, 1, parameter.default ? 1 : 0);
    case 'enum':
      return fields(
        'Choice',
        0,
        parameter.values.length - 1,
        Math.max(0, parameter.values.indexOf(parameter.default)),
        '',
        parameter.values,
      );
  }
}

function renderParameterAdd(parameter: Parameter): string {
  const pid = `juce::ParameterID { ${cppString(parameter.id)}, 1 }`;
  const name = cppString(parameter.label);
  switch (parameter.type) {
    case 'float':
      return `        layout.add(std::make_unique<juce::AudioParameterFloat>(${pid}, ${name}, juce::NormalisableRange<float>(${cppFloat(parameter.min)}, ${cppFloat(parameter.max)}), ${cppFloat(parameter.default)}));`;
    case 'int':
      return `        layout.add(std::make_unique<juce::AudioParameterInt>(${pid}, ${name}, ${cppInt(parameter.min)}, ${cppInt(parameter.max)}, ${cppInt(parameter.default)}));`;
    case 'bool':
      return `        layout.add(std::make_unique<juce::AudioParameterBool>(${pid}, ${name}, ${parameter.default ? 'true' : 'false'}));`;
    case 'enum': {
      const choices = parameter.values.map(cppString).join(', ');
      const index = Math.max(0, parameter.values.indexOf(parameter.default));
      return `        layout.add(std::make_unique<juce::AudioParameterChoice>(${pid}, ${name}, juce::StringArray { ${choices} }, ${index}));`;
    }
  }
}

function renderEditorHeader(): string {
  return `${HEADER}#pragma once

#include <juce_audio_processors/juce_audio_processors.h>
#include <soundor/runtime/DevSession.h>
#include <soundor/runtime/RuntimeHost.h>

#include <map>
#include <memory>
#include <string>

#include "SoundorProcessor.h"

namespace ${NS}
{
    // Base editor: the plugin view, and the owner of this view's JavaScript
    // runtime. The runtime is created with the view and destroyed with it;
    // ~60 times a second it receives parameter changes and runs pending jobs.
    // Under \`soundor dev\` it is replaced by a fresh one on every UI build, so
    // do not keep the reference runtimeHost() returns.
    // Derive your plugin's editor from this.
    class AudioProcessorEditor : public juce::AudioProcessorEditor, private juce::Timer
    {
    public:
        explicit AudioProcessorEditor(AudioProcessor& owner);
        ~AudioProcessorEditor() override;

        void paint(juce::Graphics&) override;

        // The view's input goes to the UI (soundor:ui); what it leaves
        // unhandled (keys, wheel) goes on to the host.
        void mouseMove(const juce::MouseEvent&) override;
        void mouseEnter(const juce::MouseEvent&) override;
        void mouseExit(const juce::MouseEvent&) override;
        void mouseDown(const juce::MouseEvent&) override;
        void mouseDrag(const juce::MouseEvent&) override;
        void mouseUp(const juce::MouseEvent&) override;
        void mouseWheelMove(const juce::MouseEvent&, const juce::MouseWheelDetails&) override;
        bool keyPressed(const juce::KeyPress&) override;
        bool keyStateChanged(bool isKeyDown) override;
        void focusLost(FocusChangeType) override;

    protected:
#if SOUNDOR_UI_DEV
        RuntimeHost& runtimeHost() noexcept { return session->host(); }
#else
        RuntimeHost& runtimeHost() noexcept { return *host; }
#endif

        AudioProcessor& processorRef;

    private:
        void timerCallback() override;
        void deliver(const ui::PointerInput& input);

        // What the UI was last drawn into, at device resolution.
        juce::Image canvas;
        bool releaseKeys(bool all);

        // Keys held down, by JUCE key code, with their Web names: JUCE reports
        // presses only, so releases are found by polling.
        std::map<int, std::string> heldKeys;

#if SOUNDOR_UI_DEV
        std::unique_ptr<DevSession> session;
#else
        std::unique_ptr<RuntimeHost> host;
#endif

        JUCE_DECLARE_NON_COPYABLE(AudioProcessorEditor)
    };
} // namespace ${NS}
`;
}

function renderEditorSource(): string {
  return `${HEADER}#include "SoundorEditor.h"

#include <soundor/backend/JuceHttpClient.h>
#include <soundor/backend/JuceInput.h>
#include <soundor/backend/JuceParameterHost.h>
#include <soundor/platform/FileLog.h>

#include <filesystem>
#include <string>
#include <string_view>

#if SOUNDOR_HAS_UI
namespace ${NS}::embedded
{
    // The plugin UI bundle, embedded by setup.cmake.
    std::span<const platform::EmbeddedFile> pluginUi();
} // namespace ${NS}::embedded
#endif

namespace ${NS}
{
    namespace
    {
        void logToJuce(js::LogLevel level, std::string_view message)
        {
            static constexpr const char* prefixes[] = { "[soundor] ", "[soundor] ", "[soundor] warning: ",
                                                        "[soundor] error: " };
            juce::Logger::writeToLog(juce::String(prefixes[static_cast<int>(level)])
                                     + juce::String::fromUTF8(message.data(), static_cast<int>(message.size())));
        }

#if SOUNDOR_UI_DEV
        // A path setup.cmake passed as hex-encoded UTF-8.
        std::filesystem::path pathFromHex(std::string_view hex)
        {
            std::u8string bytes;
            for (std::size_t i = 0; i + 1 < hex.size(); i += 2)
                bytes.push_back(static_cast<char8_t>(std::stoi(std::string(hex.substr(i, 2)), nullptr, 16)));
            return { bytes };
        }
#endif
    } // namespace

    AudioProcessorEditor::AudioProcessorEditor(AudioProcessor& owner)
        : juce::AudioProcessorEditor(owner), processorRef(owner)
    {
        RuntimeHost::Options options;
        options.runtime.log = logToJuce;
        options.pluginId = AudioProcessor::pluginId;
        options.pluginName = AudioProcessor::pluginName;
        options.http = std::make_shared<backend::JuceHttpClient>();
        options.clipboard = std::make_shared<backend::JuceClipboard>();
        options.hostInfo = std::make_shared<backend::JuceHostInfo>(owner, owner.transportCapture());
        // <user application data>/Soundor/<plugin id>: soundor:storage and soundor:fs.
        options.dataDirectory = std::filesystem::path(
            juce::File::getSpecialLocation(juce::File::userApplicationDataDirectory)
                .getChildFile("Soundor")
                .getChildFile(AudioProcessor::pluginId)
                .getFullPathName()
                .toWideCharPointer());
        options.parameters =
            std::make_shared<backend::JuceParameterHost>(owner.getParameters(), AudioProcessor::parameterInfos());
        options.installModules = [&owner](js::Context& context)
        {
            if (auto api = owner.createNativeApi())
                native::install(context, std::move(api));
        };
#if SOUNDOR_UI_DEV
        // soundor dev: the UI comes from the bundle the CLI keeps rebuilding,
        // and its log goes to the terminal running soundor dev as well.
        options.runtime.log = [file = platform::fileLogSink(pathFromHex(SOUNDOR_UI_DEV_LOG_HEX),
                                                            AudioProcessor::pluginName)](js::LogLevel level,
                                                                                         std::string_view message)
        {
            logToJuce(level, message);
            file(level, message);
        };
        session = std::make_unique<DevSession>(DevSession::Options {
            .host = std::move(options),
            .bundleDirectory = pathFromHex(SOUNDOR_UI_DEV_DIR_HEX),
        });
#else
    #if SOUNDOR_HAS_UI
        options.resources = std::make_shared<platform::EmbeddedResources>(embedded::pluginUi());
        options.entry = "/bundle.js";
    #endif
        host = std::make_unique<RuntimeHost>(std::move(options));
#endif

        setWantsKeyboardFocus(true);
        setOpaque(true);
        setSize(800, 600);
        startTimerHz(60);
    }

    AudioProcessorEditor::~AudioProcessorEditor()
    {
        stopTimer();
#if SOUNDOR_UI_DEV
        session.reset();
#else
        host.reset();
#endif
    }

    void AudioProcessorEditor::timerCallback()
    {
        // Every frame, so a reloaded UI (soundor dev) gets the size at once.
        const auto* display = juce::Desktop::getInstance().getDisplays().getDisplayForRect(getScreenBounds());
        const double displayScale = display != nullptr ? display->scale : 1.0;
        auto& surface = runtimeHost().surface();
        surface.setSize({ static_cast<float>(getWidth()), static_cast<float>(getHeight()) });
        surface.setScale(static_cast<float>(displayScale * juce::Component::getApproximateScaleFactorForComponent(this)));
#if SOUNDOR_UI_DEV
        session->tick();
#else
        host->tick();
#endif
        if (runtimeHost().needsRender())
            repaint();
    }

    void AudioProcessorEditor::deliver(const ui::PointerInput& input)
    {
        runtimeHost().surface().pointer(input);
        runtimeHost().runtime().runPendingJobs();
    }

    void AudioProcessorEditor::mouseMove(const juce::MouseEvent& event)
    {
        deliver(backend::pointerInput(event, ui::PointerInput::Phase::Move));
    }

    void AudioProcessorEditor::mouseEnter(const juce::MouseEvent& event)
    {
        deliver(backend::pointerInput(event, ui::PointerInput::Phase::Move));
    }

    void AudioProcessorEditor::mouseExit(const juce::MouseEvent& event)
    {
        deliver(backend::pointerInput(event, ui::PointerInput::Phase::Leave));
    }

    void AudioProcessorEditor::mouseDown(const juce::MouseEvent& event)
    {
        deliver(backend::pointerInput(event, ui::PointerInput::Phase::Down));
    }

    void AudioProcessorEditor::mouseDrag(const juce::MouseEvent& event)
    {
        deliver(backend::pointerInput(event, ui::PointerInput::Phase::Move));
    }

    void AudioProcessorEditor::mouseUp(const juce::MouseEvent& event)
    {
        deliver(backend::pointerInput(event, ui::PointerInput::Phase::Up));
    }

    void AudioProcessorEditor::mouseWheelMove(const juce::MouseEvent& event, const juce::MouseWheelDetails& wheel)
    {
        const bool handled = runtimeHost().surface().wheel(backend::wheelInput(event.position, event.mods, wheel));
        runtimeHost().runtime().runPendingJobs();
        if (! handled)
            juce::AudioProcessorEditor::mouseWheelMove(event, wheel);
    }

    bool AudioProcessorEditor::keyPressed(const juce::KeyPress& key)
    {
        const std::string name = backend::keyName(key);
        if (name.empty())
            return false;
        const bool repeat = ! heldKeys.emplace(key.getKeyCode(), name).second;
        auto& surface = runtimeHost().surface();
        bool handled = surface.key({ .down = true,
                                     .key = name,
                                     .repeat = repeat,
                                     .modifiers = backend::modifiersOf(key.getModifiers()) });
        if (! handled)
            if (const std::string text = backend::typedText(key); ! text.empty())
                handled = surface.text({ text });
        runtimeHost().runtime().runPendingJobs();
        return handled;
    }

    bool AudioProcessorEditor::keyStateChanged(bool isKeyDown)
    {
        return ! isKeyDown && releaseKeys(false);
    }

    void AudioProcessorEditor::focusLost(FocusChangeType)
    {
        releaseKeys(true);
    }

    bool AudioProcessorEditor::releaseKeys(bool all)
    {
        bool handled = false;
        const auto modifiers = backend::modifiersOf(juce::ModifierKeys::currentModifiers);
        for (auto key = heldKeys.begin(); key != heldKeys.end();)
        {
            if (! all && juce::KeyPress::isKeyCurrentlyDown(key->first))
            {
                ++key;
                continue;
            }
            handled = runtimeHost().surface().key(
                          { .down = false, .key = key->second, .repeat = false, .modifiers = modifiers })
                      || handled;
            key = heldKeys.erase(key);
        }
        runtimeHost().runtime().runPendingJobs();
        return handled;
    }

    void AudioProcessorEditor::paint(juce::Graphics& g)
    {
        g.fillAll(getLookAndFeel().findColour(juce::ResizableWindow::backgroundColourId));
        auto& surface = runtimeHost().surface();
        const int width = juce::roundToInt(static_cast<float>(getWidth()) * surface.scale());
        const int height = juce::roundToInt(static_cast<float>(getHeight()) * surface.scale());
        if (width <= 0 || height <= 0)
            return;
        if (canvas.getWidth() != width || canvas.getHeight() != height)
            canvas = juce::Image(juce::Image::ARGB, width, height, false, juce::SoftwareImageType());
        {
            // JUCE's ARGB pixels are Skia's native 32-bit premultiplied format.
            juce::Image::BitmapData pixels(canvas, juce::Image::BitmapData::writeOnly);
            runtimeHost().render({ pixels.data, width, height, static_cast<std::size_t>(pixels.lineStride) });
        }
        g.drawImage(canvas, getLocalBounds().toFloat());
    }
} // namespace ${NS}
`;
}

// ── Value helpers ───────────────────────────────────────────────────────────

/** A quoted CMake argument; JSON escaping is a valid subset of CMake's. */
function cmakeString(value: string): string {
  return JSON.stringify(value).replaceAll('$', '\\$');
}

function cppString(value: string): string {
  return JSON.stringify(value);
}

function cppIdent(id: string): string {
  const ident = id.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[0-9]/.test(ident) ? `_${ident}` : ident;
}

/** A C++ path string with forward slashes (CMake accepts them everywhere). */
function cmakePath(path: string): string {
  return path.replaceAll('\\', '/');
}

function cppDouble(value: number): string {
  return Number.isInteger(value) ? `${value}.0` : `${value}`;
}

function cppFloat(value: number): string {
  return Number.isInteger(value) ? `${value}.0f` : `${value}f`;
}

function cppInt(value: number): string {
  return `${Math.trunc(value)}`;
}
