/**
 * Generates the C++ side of `soundor:native` from the config's native API:
 *
 * - `soundor/native/SoundorNative.h` — the types (structs, enums, handle base
 *   classes) and the `NativeApi` interface the plugin implements, plus
 *   `install()`, which makes the module importable in a JavaScript context.
 *   Plain C++: no engine headers, so plugin code including it never sees
 *   QuickJS.
 * - `soundor/native/SoundorNative.cpp` — the QuickJS bindings: argument
 *   validation, conversions, exception and promise plumbing, written against
 *   the runtime's internal `js/Bindings.h` helpers.
 *
 * Output is deterministic and readable but not run through clang-format; like
 * all generated code it is excluded from the format and lint checks, and is
 * never edited by hand.
 */

import type {
  BinaryTypeName,
  NativeApiModel,
  NativeField,
  NativeMethodModel,
  NativeType,
  NativeTypeModel,
} from '@soundor/core';
import { enumeratorName } from '@soundor/core';

export interface NativeCodegenFile {
  readonly path: string;
  readonly contents: string;
}

const HEADER = '// This file was generated by Soundor. Do not edit.\n';
const NAMESPACE = 'soundor::inline SOUNDOR_ABI_NAMESPACE::native';

const BINARY_ELEMENT: Record<BinaryTypeName, string> = {
  ArrayBuffer: 'std::byte',
  Uint8Array: 'std::uint8_t',
  Int32Array: 'std::int32_t',
  Float32Array: 'float',
  Float64Array: 'double',
};

/** The generated `soundor:native` C++ sources, paths relative to the gen root. */
export function generateNativeModuleSources(
  model: NativeApiModel,
): NativeCodegenFile[] {
  return [
    { path: 'soundor/native/SoundorNative.h', contents: renderHeader(model) },
    { path: 'soundor/native/SoundorNative.cpp', contents: renderSource(model) },
  ];
}

// ── Header ──────────────────────────────────────────────────────────────────

function renderHeader(model: NativeApiModel): string {
  const types = model.types.map(renderTypeDeclaration);
  const methods = model.methods.map(
    (method) => `        virtual ${methodSignature(method)} = 0;`,
  );
  const apiBody = methods.length > 0 ? `\n${methods.join('\n')}` : '';
  return `${HEADER}#pragma once

#include <soundor/js/Context.h>
#include <soundor/js/Promise.h>

#include <cstddef>
#include <cstdint>
#include <memory>
#include <span>
#include <string>
#include <vector>

namespace ${NAMESPACE}
{
${types.map((type) => `${type}\n\n`).join('')}    // The plugin's native API, declared under \`native.methods\` in
    // soundor.config. Implement it in the plugin and install() it into each
    // JavaScript context; JavaScript calls it through \`soundor:native\`.
    //
    // Methods run on the UI/message thread and must not block it. Arguments
    // that view binary data are only valid until the method returns. Async
    // methods receive a js::Promise to settle later, on the same thread.
    class NativeApi
    {
    public:
        virtual ~NativeApi() = default;${apiBody}
    };

    // Makes \`soundor:native\` importable in \`context\`, backed by \`api\`. Call
    // before evaluating code that imports it; the context keeps \`api\` alive.
    void install(js::Context& context, std::shared_ptr<NativeApi> api);
} // namespace ${NAMESPACE}
`;
}

function renderTypeDeclaration(type: NativeTypeModel): string {
  switch (type.kind) {
    case 'enum':
      return `    enum class ${type.name}
    {
${type.values.map((value) => `        ${enumeratorName(value)}, // ${JSON.stringify(value)}`).join('\n')}
    };`;
    case 'handle':
      return `    // Opaque to JavaScript: derive the native object from this class.
    class ${type.name}
    {
    public:
        virtual ~${type.name}() = default;
    };`;
    case 'struct':
      return `    struct ${type.name}
    {
${type.fields.map((field) => `        ${valueType(field.type)} ${field.name} {};`).join('\n')}
    };`;
  }
}

function methodSignature(method: NativeMethodModel): string {
  const params = method.args.map(
    (arg) => `${argumentType(arg.type)} ${arg.name}`,
  );
  if (method.async) {
    params.push(`js::Promise<${promiseValueType(method.returns)}> promise`);
    return `void ${method.name}(${params.join(', ')})`;
  }
  return `${resultType(method.returns)} ${method.name}(${params.join(', ')})`;
}

/** How a value is passed into a native method. */
function argumentType(type: NativeType): string {
  if (type.kind === 'binary')
    return `std::span<const ${BINARY_ELEMENT[type.name]}>`;
  return valueType(type);
}

/** How a value is returned or stored in a struct. */
function valueType(type: NativeType): string {
  switch (type.kind) {
    case 'void':
      return 'void';
    case 'primitive':
      return { boolean: 'bool', number: 'double', string: 'std::string' }[
        type.name
      ];
    case 'binary':
      return `std::vector<${BINARY_ELEMENT[type.name]}>`;
    case 'declared':
      return type.declaration === 'handle'
        ? `std::shared_ptr<${type.name}>`
        : type.name;
    case 'array':
      return `std::vector<${valueType(type.element)}>`;
  }
}

function resultType(type: NativeType): string {
  return valueType(type);
}

function promiseValueType(type: NativeType): string {
  return type.kind === 'void' ? 'void' : valueType(type);
}

// ── Source ──────────────────────────────────────────────────────────────────

function renderSource(model: NativeApiModel): string {
  const handles = model.types.filter((type) => type.kind === 'handle');
  const enums = model.types.filter((type) => type.kind === 'enum');
  const structs = model.types.filter((type) => type.kind === 'struct');

  const { reads, writes } = conversionUsage(model);
  const sections = [
    `        // Identifies this context's NativeApi in its module data.
        const char apiKey = 0;`,
    ...handles.map(
      (type) =>
        `        const bind::HandleType ${handleTypeName(type.name)} { ${JSON.stringify(type.name)} };`,
    ),
    ...enums.map((type) =>
      renderEnumConversions(type, reads.has(type.name), writes.has(type.name)),
    ),
    ...structs.map((type) =>
      renderStructConversions(
        type,
        reads.has(type.name),
        writes.has(type.name),
      ),
    ),
    ...model.methods.flatMap((method) =>
      method.async && method.returns.kind !== 'void'
        ? [renderResolver(method), renderBinding(method)]
        : [renderBinding(method)],
    ),
  ];

  const exportNames = model.methods.map((method) =>
    JSON.stringify(method.name),
  );
  const exportSetters = model.methods.map(
    (method) =>
      `JS_SetModuleExport(ctx, module, ${JSON.stringify(method.name)}, JS_NewCFunction(ctx, ${bindingName(method)}, ${JSON.stringify(method.name)}, ${method.args.length})) == 0`,
  );
  const initializeBody =
    exportSetters.length > 0
      ? `return ${exportSetters.join('\n                       && ')};`
      : 'return true;';
  const initializeParams =
    exportSetters.length > 0
      ? 'JSContext* ctx, JSModuleDef* module'
      : 'JSContext*, JSModuleDef*';

  return `${HEADER}#include "SoundorNative.h"

#include "js/Bindings.h"

#include <array>
#include <stdexcept>
#include <string_view>
#include <utility>

namespace ${NAMESPACE}
{
    namespace
    {
        using js::bind::read;
        using js::bind::write;
        namespace bind = js::bind;

${sections.join('\n\n')}
    } // namespace

    void install(js::Context& context, std::shared_ptr<NativeApi> api)
    {
        if (api == nullptr)
            throw std::invalid_argument("soundor:native needs a NativeApi implementation");
        bind::setContextData(context, &apiKey, std::move(api));
        js::registerNativeModule(context, "soundor:native",
                                 {
                                     { ${exportNames.join(', ')} },
                                     [](${initializeParams})
                                     {
                                         ${initializeBody}
                                     },
                                 });
    }
} // namespace ${NAMESPACE}
`;
}

function handleTypeName(name: string): string {
  return `k${name}Handle`;
}

/**
 * Which declared types are converted from JavaScript (arguments) and which to
 * JavaScript (results), following struct fields. Only those conversions are
 * generated, so the output has no unused functions.
 */
function conversionUsage(model: NativeApiModel): {
  reads: Set<string>;
  writes: Set<string>;
} {
  const structs = new Map(
    model.types.flatMap((type) =>
      type.kind === 'struct' ? [[type.name, type] as const] : [],
    ),
  );
  const mark = (type: NativeType, into: Set<string>): void => {
    if (type.kind === 'array') return mark(type.element, into);
    if (type.kind !== 'declared' || into.has(type.name)) return;
    into.add(type.name);
    for (const field of structs.get(type.name)?.fields ?? [])
      mark(field.type, into);
  };
  const reads = new Set<string>();
  const writes = new Set<string>();
  for (const method of model.methods) {
    for (const arg of method.args) mark(arg.type, reads);
    mark(method.returns, writes);
  }
  return { reads, writes };
}

function renderEnumConversions(
  type: Extract<NativeTypeModel, { kind: 'enum' }>,
  readable: boolean,
  writable: boolean,
): string {
  const values = `k${type.name}Values`;
  const parts = [
    `        constexpr std::array<std::string_view, ${type.values.length}> ${values} { ${type.values.map((value) => JSON.stringify(value)).join(', ')} };`,
  ];
  if (readable) {
    parts.push(`        bool read(JSContext* ctx, JSValueConst value, const bind::Path& path, ${type.name}& out)
        {
            std::size_t index = 0;
            if (! bind::readEnum(ctx, value, path, ${values}, index))
                return false;
            out = static_cast<${type.name}>(index);
            return true;
        }`);
  }
  if (writable) {
    parts.push(`        JSValue write(JSContext* ctx, ${type.name} value)
        {
            return bind::writeEnum(ctx, ${values}.at(static_cast<std::size_t>(value)));
        }`);
  }
  return parts.join('\n\n');
}

function renderStructConversions(
  type: Extract<NativeTypeModel, { kind: 'struct' }>,
  readable: boolean,
  writable: boolean,
): string {
  const reads = type.fields.map(
    (field) => `            {
                const bind::Field field(ctx, value, ${JSON.stringify(field.name)}, path);
                if (! field || ! ${readExpression(field.type, 'ctx', 'field.value()', 'field.path()', `out.${field.name}`)})
                    return false;
            }`,
  );
  const writes = type.fields.map(
    (field) =>
      `            object.set(${JSON.stringify(field.name)}, ${writeExpression(field.type, 'ctx', `value.${field.name}`)});`,
  );
  const parts: string[] = [];
  if (readable) {
    parts.push(`        bool read(JSContext* ctx, JSValueConst value, const bind::Path& path, ${type.name}& out)
        {
            if (! bind::expectObject(ctx, value, path))
                return false;
${reads.join('\n')}
            return true;
        }`);
  }
  if (writable) {
    parts.push(`        JSValue write(JSContext* ctx, ${type.name} value)
        {
            bind::ObjectBuilder object(ctx);
${writes.join('\n')}
            return object.release();
        }`);
  }
  return parts.join('\n\n');
}

function renderResolver(method: NativeMethodModel): string {
  const type = valueType(method.returns);
  return `        void ${resolverName(method)}(js::detail::PendingPromise& pending, ${type}&& value)
        {
            bind::resolvePromise(pending, [&](JSContext* ctx) { return ${writeExpression(method.returns, 'ctx', 'value')}; });
        }`;
}

function renderBinding(method: NativeMethodModel): string {
  const name = JSON.stringify(method.name);
  const reads = method.args.map((arg, index) => renderArgumentRead(arg, index));
  const callArgs = method.args.map(
    (arg) => `std::move(${argumentVariable(arg)})`,
  );
  const call = `api->${method.name}(${[...callArgs, ...(method.async ? ['promiseHandle'] : [])].join(', ')})`;

  let tail: string;
  if (method.async) {
    const promiseType = `js::Promise<${promiseValueType(method.returns)}>`;
    const resolver =
      method.returns.kind === 'void'
        ? 'bind::resolvePromiseWithUndefined'
        : resolverName(method);
    tail = `                std::shared_ptr<js::detail::PendingPromise> pending;
                JSValue promise = bind::newPromise(ctx, ${name}, pending);
                if (JS_IsException(promise))
                    return promise;
                const ${promiseType} promiseHandle(pending, ${resolver});
                bind::startAsync(*pending, [&] { ${call}; });
                return promise;`;
  } else if (method.returns.kind === 'void') {
    tail = `                ${call};
                return JS_UNDEFINED;`;
  } else {
    tail = `                return ${writeExpression(method.returns, 'ctx', call, true)};`;
  }

  const pathLine =
    method.args.length > 0
      ? `                const bind::Path call { ${name} };\n`
      : '';
  const argcName = 'argc';
  const argvName = method.args.length > 0 ? 'argv' : '';
  return `        JSValue ${bindingName(method)}(JSContext* ctx, JSValueConst, int ${argcName}, JSValueConst* ${argvName})
        {
            return bind::invoke(ctx, ${name},
                                [&]() -> JSValue
                                {
                auto* api = bind::contextData<NativeApi>(ctx, &apiKey);
                if (api == nullptr)
                    return JS_ThrowInternalError(ctx, "soundor:native is not installed in this context");
                if (! bind::expectArgumentCount(ctx, ${name}, argc, ${method.args.length}))
                    return JS_EXCEPTION;
${pathLine}${reads.join('\n')}${reads.length > 0 ? '\n' : ''}${tail}
                                });
        }`.replace(/JSValueConst\* \)/, 'JSValueConst*)');
}

function renderArgumentRead(arg: NativeField, index: number): string {
  const variable = argumentVariable(arg);
  return `                ${argumentType(arg.type)} ${variable} {};
                if (! ${readExpression(arg.type, 'ctx', `argv[${index}]`, `call.field(${JSON.stringify(arg.name)})`, variable)})
                    return JS_EXCEPTION;`;
}

/** A C++ boolean expression reading `value` at `path` into `out`. */
function readExpression(
  type: NativeType,
  ctx: string,
  value: string,
  path: string,
  out: string,
): string {
  if (type.kind === 'declared' && type.declaration === 'handle') {
    return `bind::read(${ctx}, ${value}, ${path}, ${handleTypeName(type.name)}, ${out})`;
  }
  if (type.kind === 'array') {
    const element = valueType(type.element);
    const inner = readExpression(
      type.element,
      'elementCtx',
      'element',
      'elementPath',
      'item',
    );
    return `bind::readArray(${ctx}, ${value}, ${path}, ${out}, [](JSContext* elementCtx, JSValueConst element, const bind::Path& elementPath, ${element}& item) { return ${inner}; })`;
  }
  return `read(${ctx}, ${value}, ${path}, ${out})`;
}

/**
 * A C++ expression converting `value` (consumed) into a new JSValue. A named
 * `value` is moved from; a temporary (a call result) is passed as is.
 */
function writeExpression(
  type: NativeType,
  ctx: string,
  value: string,
  temporary = false,
): string {
  const consumed = temporary ? value : `std::move(${value})`;
  switch (type.kind) {
    case 'void':
      return 'JS_UNDEFINED';
    case 'primitive':
      return `write(${ctx}, ${value})`;
    case 'binary':
      return `write(${ctx}, ${consumed})`;
    case 'declared':
      return type.declaration === 'handle'
        ? `bind::writeHandle(${ctx}, ${handleTypeName(type.name)}, ${consumed})`
        : `write(${ctx}, ${consumed})`;
    case 'array': {
      const element = valueType(type.element);
      const inner = writeExpression(type.element, 'elementCtx', 'item');
      return `bind::writeArray(${ctx}, ${consumed}, [](JSContext* elementCtx, ${element}&& item) { return ${inner}; })`;
    }
  }
}

function argumentVariable(arg: NativeField): string {
  return `arg_${arg.name}`;
}

function bindingName(method: NativeMethodModel): string {
  return `call_${method.name}`;
}

function resolverName(method: NativeMethodModel): string {
  return `resolve_${method.name}`;
}
