export { defineRuntime } from './runtime';

// Runtime contract + config surface, re-exported so a runtime author imports
// everything from one place.
export type {
  DoctorCheck,
  DoctorReport,
  LifecycleContext,
  Runtime,
  RuntimeConfig,
  RuntimeDescriptor,
  RuntimeFactory,
  PluginIdentity,
  RuntimeMode,
  RuntimePhase,
  SoundorConfig,
  LiveUiContext,
  UiBundleContext,
  ResolvedRuntime,
  DispatchContextInput,
  MacosSigning,
  MacosSigningConfig,
  MacosSigningSource,
  SigningConfig,
  SigningContext,
} from '@soundor/config';
export {
  AD_HOC_IDENTITY,
  ConfigError,
  MACOS_KEYCHAIN_ENV,
  MACOS_SIGNING_IDENTITY_ENV,
  resolveRuntime,
  resolveSigning,
  runPhase,
} from '@soundor/config';

// Host helpers + shared error taxonomy from @soundor/core.
export {
  createCodegenSink,
  createConsoleLogger,
  createNodeFileSystem,
  createProjectPaths,
  checkGeneratedFiles,
  generateSoundorFiles,
  nullCodegenSink,
  writeGeneratedFiles,
  probeCommand,
  runCommand,
  CommandFailedError,
  EXIT_CODES,
  EnvError,
  GeneratedFilesOutOfDateError,
  RuntimeError,
  SoundorError,
  UnknownRuntimeError,
  exitCodeFor,
  describeNativeApi,
  nativeAbiNamespace,
} from '@soundor/core';
export type {
  CodegenFile,
  CodegenSink,
  CollectingCodegenSink,
  CommandProbe,
  CommandRunner,
  ProbeResult,
  RunCommandOptions,
  CoreBaseParameter,
  CoreBoolParameter,
  CoreEnumParameter,
  CoreFloatParameter,
  CoreIntParameter,
  CoreParameter,
  CorePluginIdentity,
  CoreRuntimeDescriptor,
  CoreSoundorConfig,
  FileSystemHost,
  GeneratedFileChange,
  Logger,
  ProjectPaths,
  SoundorErrorCode,
  SoundorIssue,
  NativeApiDeclaration,
  NativeApiModel,
  NativeType,
} from '@soundor/core';
