/**
 * The TypeScript contract of `soundor:native` for the Web: what
 * `runtimes/web/src/native.ts` implements. The JUCE runtime generates a C++
 * interface from the same model; here the plugin's calls reach the user's
 * TypeScript directly, with no serialization in between.
 *
 * Types match the plugin-facing declaration (`.soundor/generated/native.d.ts`)
 * so values cross unchanged: arguments as the plugin passes them (readonly
 * arrays), results as it receives them, and handles as opaque objects made
 * with each handle type's `wrap()`.
 */

import type { NativeApiModel, NativeType } from '@soundor/runtime-sdk';

type NativeTypeModel = NativeApiModel['types'][number];

const HEADER = '// This file was generated by Soundor. Do not edit.\n\n';

/** The generated `native.ts`, from a resolved native API model. */
export function renderWebNative(model: NativeApiModel): string {
  const handles = model.types.some((type) => type.kind === 'handle');
  const imports = handles
    ? "import {\n  defineHandle,\n  type WebNativeHandle,\n} from '@soundor/web-runtime/client';\n\n"
    : '';
  const types = model.types.map(renderType);
  const methods = model.methods.map((method) => {
    const args = method.args
      .map((arg) => `${arg.name}: ${tsType(arg.type, 'argument')}`)
      .join(', ');
    const result = tsType(method.returns, 'result');
    return `  ${method.name}(${args}): ${method.async ? `Promise<${result}>` : result};`;
  });
  const api =
    methods.length === 0
      ? 'export type WebNativeApi = Record<never, never>;\n'
      : `export interface WebNativeApi {\n${methods.join('\n')}\n}\n`;
  return `${HEADER}${imports}${types.map((type) => `${type}\n\n`).join('')}/**
 * The plugin's native API (soundor:native), as runtimes/web/src/native.ts
 * implements it for the Web. A method added to soundor.config is missing
 * here until it is implemented.
 */
${api}`;
}

function renderType(type: NativeTypeModel): string {
  switch (type.kind) {
    case 'handle':
      return [
        `/** An opaque reference to a ${type.name}: \`${type.name}.wrap(value)\` makes one, \`${type.name}.unwrap(handle)\` gets the value back. */`,
        `export type ${type.name} = WebNativeHandle<'${type.name}'>;`,
        `export const ${type.name} = defineHandle('${type.name}');`,
      ].join('\n');
    case 'enum':
      return `export type ${type.name} = ${type.values.map(quote).join(' | ')};`;
    case 'struct': {
      const fields = type.fields.map(
        (field) => `  ${field.name}: ${tsType(field.type, 'result')};`,
      );
      return [`export interface ${type.name} {`, ...fields, '}'].join('\n');
    }
  }
}

/** A string literal in single quotes, as the project writes them. */
function quote(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

/** Arguments arrive as readonly arrays; results may be any array. */
function tsType(type: NativeType, position: 'argument' | 'result'): string {
  switch (type.kind) {
    case 'void':
      return 'void';
    case 'primitive':
    case 'binary':
    case 'declared':
      return type.name;
    case 'array': {
      const element = tsType(type.element, position);
      return position === 'argument' ? `readonly ${element}[]` : `${element}[]`;
    }
  }
}
