import { resolve as resolvePath, sep } from 'node:path';

import type { CodegenFile } from './codegen';
import { SoundorError } from './errors';
import type { FileSystemHost } from './filesystem';

const HEADER = '// This file was generated by Soundor. Do not edit.\n\n';

export interface CoreRuntimeDescriptor {
  readonly id: string;
}

export interface CoreBaseParameter {
  readonly id: string;
  readonly label: string;
  readonly onChange?: string;
}

export interface CoreFloatParameter extends CoreBaseParameter {
  readonly type: 'float';
  readonly min: number;
  readonly max: number;
  readonly default: number;
  readonly unit?: string;
}

export interface CoreIntParameter extends CoreBaseParameter {
  readonly type: 'int';
  readonly min: number;
  readonly max: number;
  readonly default: number;
  readonly unit?: string;
}

export interface CoreBoolParameter extends CoreBaseParameter {
  readonly type: 'bool';
  readonly default: boolean;
}

export interface CoreEnumParameter extends CoreBaseParameter {
  readonly type: 'enum';
  readonly values: readonly string[];
  readonly default: string;
}

export type CoreParameter =
  | CoreFloatParameter
  | CoreIntParameter
  | CoreBoolParameter
  | CoreEnumParameter;

export interface CoreNativeMethod {
  readonly name: string;
  readonly input: string;
  readonly output: string;
}

export interface CoreSoundorConfig {
  readonly runtimes?: readonly CoreRuntimeDescriptor[];
  readonly parameters: readonly CoreParameter[];
  readonly nativeMethods?: readonly CoreNativeMethod[];
}

export interface GeneratedFileChange {
  readonly path: string;
  readonly kind: 'missing' | 'stale';
}

export interface GeneratedFileWriteResult {
  readonly path: string;
  readonly status: 'created' | 'updated' | 'unchanged';
}

export interface GeneratedFileCheckResult {
  readonly path: string;
  readonly status: 'up-to-date';
}

export class GeneratedFilesOutOfDateError extends SoundorError {
  readonly changes: GeneratedFileChange[];

  constructor(changes: readonly GeneratedFileChange[]) {
    super(
      `Generated files are out of date: ${changes.map((change) => change.path).join(', ')}.`,
      {
        code: 'CONFIG',
        issues: changes.map((change) => ({
          path: change.path,
          message:
            change.kind === 'missing'
              ? 'generated file is missing'
              : 'generated file contents are stale',
        })),
      },
    );
    this.name = 'GeneratedFilesOutOfDateError';
    this.changes = [...changes];
  }
}

export function generateSoundorFiles(config: CoreSoundorConfig): CodegenFile[] {
  return [
    { path: 'parameters.ts', contents: renderParametersTs(config.parameters) },
    {
      path: 'parameters.json',
      contents: `${stableJson({ parameters: sortedParameters(config.parameters) })}\n`,
    },
    {
      path: 'native-methods.ts',
      contents: renderNativeMethodsTs(config.nativeMethods ?? []),
    },
    { path: 'soundor.d.ts', contents: renderSoundorDts() },
  ];
}

export async function writeGeneratedFiles(
  fs: FileSystemHost,
  outputDir: string,
  files: readonly CodegenFile[],
): Promise<GeneratedFileWriteResult[]> {
  const results: GeneratedFileWriteResult[] = [];
  for (const file of sortFiles(files)) {
    const target = generatedTarget(fs, outputDir, file.path);
    const exists = await fs.exists(target);
    if (exists && (await fs.read(target)) === file.contents) {
      results.push({ path: file.path, status: 'unchanged' });
      continue;
    }
    await fs.write(target, file.contents);
    results.push({ path: file.path, status: exists ? 'updated' : 'created' });
  }
  return results;
}

export async function checkGeneratedFiles(
  fs: FileSystemHost,
  outputDir: string,
  files: readonly CodegenFile[],
): Promise<GeneratedFileCheckResult[]> {
  const changes: GeneratedFileChange[] = [];
  const sorted = sortFiles(files);
  for (const file of sorted) {
    const target = generatedTarget(fs, outputDir, file.path);
    if (!(await fs.exists(target))) {
      changes.push({ path: file.path, kind: 'missing' });
      continue;
    }
    if ((await fs.read(target)) !== file.contents) {
      changes.push({ path: file.path, kind: 'stale' });
    }
  }
  if (changes.length > 0) throw new GeneratedFilesOutOfDateError(changes);
  return sorted.map((file) => ({ path: file.path, status: 'up-to-date' }));
}

function renderParametersTs(parameters: readonly CoreParameter[]): string {
  const sorted = sortedParameters(parameters);
  const parameterEntries = sorted.map(
    (parameter) =>
      `  ${quoteProperty(parameter.id)}: ${renderParameterObject(parameter)},`,
  );
  const valueMapEntries = sorted.map(
    (parameter) =>
      `  ${quoteProperty(parameter.id)}: ${parameterValueType(parameter)};`,
  );

  return ensureFinalNewline(
    `${HEADER}export const parameters = {\n${parameterEntries.join('\n')}\n} as const;\n\nexport type ParameterId = keyof typeof parameters;\n\nexport type ParameterInfoMap = typeof parameters;\n\nexport type ParameterValueMap = {\n${valueMapEntries.join('\n')}\n};\n\nexport type ParameterValue<T extends ParameterId> = ParameterValueMap[T];\n\nexport const useParamInfo = parameters;\n`,
  );
}

function renderNativeMethodsTs(methods: readonly CoreNativeMethod[]): string {
  const sorted = [...methods].sort((a, b) => a.name.localeCompare(b.name));
  const aliases = [
    ...new Set(sorted.flatMap((method) => [method.input, method.output])),
  ]
    .sort((a, b) => a.localeCompare(b))
    .map((typeName) => `export type ${typeName} = unknown;`);
  const requestEntries = sorted.map(
    (method) => `  ${quoteProperty(method.name)}: ${method.input};`,
  );
  const responseEntries = sorted.map(
    (method) => `  ${quoteProperty(method.name)}: ${method.output};`,
  );

  return ensureFinalNewline(
    `${HEADER}${aliases.join('\n')}\n\nexport interface NativeMethodRequests {\n${requestEntries.join('\n')}\n}\n\nexport interface NativeMethodResponses {\n${responseEntries.join('\n')}\n}\n\nexport type NativeMethodName = keyof NativeMethodRequests;\n\nexport type NativeMethodDispatcher = {\n  [K in NativeMethodName]: (\n    request: NativeMethodRequests[K],\n  ) => Promise<NativeMethodResponses[K]>;\n};\n`,
  );
}

/**
 * A single ambient declaration file that (a) augments `@soundor/bridge`'s
 * `Soundor*` maps with the concrete param/native types and (b) declares the
 * `virtual:soundor/bridge` module the CLI's Vite plugin serves. Apps register
 * just this file (tsconfig `files`), keeping the generated `.ts` sources out of
 * their compilation.
 *
 * Two deliberate shapes make the augmentation actually take effect:
 *
 * 1. No top-level `import`/`export` statements, so the file stays a global
 *    script. A `.d.ts` with a top-level import is a module, which would turn
 *    `declare module 'virtual:soundor/bridge'` into an augmentation of a
 *    non-existent module (silently ignored) instead of the ambient declaration
 *    we need.
 * 2. The concrete generated types are pulled into top-level `type` aliases via
 *    `import(...)` — a relative `import(...)` used directly inside a
 *    `declare module '@soundor/bridge'` block resolves ambiguously and yields
 *    empty types, so the augmentation's `extends` clauses reference the aliases
 *    instead. `import(...)` in a type alias does not make the file a module.
 */
function renderSoundorDts(): string {
  return ensureFinalNewline(
    `${HEADER}type SoundorGeneratedParameterInfoMap = import('./parameters').ParameterInfoMap;\ntype SoundorGeneratedParameterValueMap = import('./parameters').ParameterValueMap;\ntype SoundorGeneratedNativeMethodRequests =\n  import('./native-methods').NativeMethodRequests;\ntype SoundorGeneratedNativeMethodResponses =\n  import('./native-methods').NativeMethodResponses;\n\ndeclare module '@soundor/bridge' {\n  interface SoundorParamInfoMap extends SoundorGeneratedParameterInfoMap {}\n  interface SoundorParamValueMap extends SoundorGeneratedParameterValueMap {}\n  interface SoundorNativeMethodRequests\n    extends SoundorGeneratedNativeMethodRequests {}\n  interface SoundorNativeMethodResponses\n    extends SoundorGeneratedNativeMethodResponses {}\n}\n\ndeclare module 'virtual:soundor/bridge' {\n  export const bridge: import('@soundor/bridge').Bridge;\n  export default bridge;\n}\n`,
  );
}

function renderParameterObject(parameter: CoreParameter): string {
  switch (parameter.type) {
    case 'float':
    case 'int':
      return renderObject({
        default: parameter.default,
        id: parameter.id,
        label: parameter.label,
        max: parameter.max,
        min: parameter.min,
        onChange: parameter.onChange,
        type: parameter.type,
        unit: parameter.unit,
      });
    case 'bool':
      return renderObject({
        default: parameter.default,
        id: parameter.id,
        label: parameter.label,
        onChange: parameter.onChange,
        type: 'bool',
      });
    case 'enum':
      return renderObject({
        default: parameter.default,
        id: parameter.id,
        label: parameter.label,
        onChange: parameter.onChange,
        type: 'enum',
        values: parameter.values,
      });
  }
}

function renderObject(value: Record<string, unknown>): string {
  const entries = Object.entries(value)
    .filter(([, entryValue]) => entryValue !== undefined)
    .sort(([a], [b]) => a.localeCompare(b));
  return `{ ${entries.map(([key, entryValue]) => `${quoteProperty(key)}: ${renderTsValue(entryValue)}`).join(', ')} }`;
}

function renderTsValue(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(renderTsValue).join(', ')}]`;
  return JSON.stringify(value);
}

function parameterValueType(parameter: CoreParameter): string {
  switch (parameter.type) {
    case 'float':
    case 'int':
      return 'number';
    case 'bool':
      return 'boolean';
    case 'enum':
      return parameter.values.map((value) => JSON.stringify(value)).join(' | ');
  }
}

function sortedParameters(
  parameters: readonly CoreParameter[],
): CoreParameter[] {
  return [...parameters].sort((a, b) => a.id.localeCompare(b.id));
}

function sortFiles(files: readonly CodegenFile[]): CodegenFile[] {
  return [...files].sort((a, b) => a.path.localeCompare(b.path));
}

function stableJson(value: unknown): string {
  return `${JSON.stringify(sortJsonValue(value), null, 2)}\n`.trimEnd();
}

function sortJsonValue(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortJsonValue);
  if (typeof value !== 'object' || value === null) return value;
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>)
      .filter(([, entryValue]) => entryValue !== undefined)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, entryValue]) => [key, sortJsonValue(entryValue)]),
  );
}

function generatedTarget(
  fs: FileSystemHost,
  outputDir: string,
  filePath: string,
): string {
  if (filePath.startsWith('/') || filePath.includes('\\')) {
    throw new SoundorError(`Unsafe generated file path: ${filePath}`, {
      code: 'INTERNAL',
    });
  }

  const base = fs.resolve(outputDir);
  const target = resolvePath(base, filePath);
  if (target !== base && !target.startsWith(`${base}${sep}`)) {
    throw new SoundorError(`Unsafe generated file path: ${filePath}`, {
      code: 'INTERNAL',
    });
  }
  return target;
}

function quoteProperty(property: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(property)
    ? property
    : JSON.stringify(property);
}

function ensureFinalNewline(value: string): string {
  return `${value.trimEnd()}\n`;
}
