import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { createNodeFileSystem, type FileSystemHost } from './filesystem';
import {
  GeneratedFilesOutOfDateError,
  checkGeneratedFiles,
  generateSoundorFiles,
  writeGeneratedFiles,
  type CoreSoundorConfig,
} from './generate';

const config: CoreSoundorConfig = {
  plugin: { id: 'com.example.plugin', name: 'Example' },
  runtimes: [{ id: 'juce' }],
  parameters: [
    { type: 'bool', id: 'bypass', label: 'Bypass', default: false },
    {
      type: 'float',
      id: 'gain',
      label: 'Gain',
      min: 0,
      max: 1,
      default: 0.5,
      unit: 'dB',
    },
    {
      type: 'enum',
      id: 'mode',
      label: 'Mode',
      values: ['mono', 'stereo'],
      default: 'stereo',
    },
    { type: 'int', id: 'voices', label: 'Voices', min: 1, max: 16, default: 4 },
  ],
  native: {
    types: { Level: { struct: { peak: 'number', rms: 'number' } } },
    methods: {
      measure: { args: { samples: 'Float32Array' }, returns: 'Level' },
      reset: {},
    },
  },
};

describe('generateSoundorFiles', () => {
  it('emits deterministic golden files', () => {
    expect(generateSoundorFiles(config)).toEqual([
      {
        path: 'globals.d.ts',
        contents: expect.stringContaining('declare function fetch('),
      },
      {
        path: 'native.d.ts',
        contents: `// This file was generated by Soundor. Do not edit.

declare module 'soundor:native' {
  export interface Level {
    peak: number;
    rms: number;
  }

  export function measure(samples: Float32Array): Level;

  export function reset(): void;
}
`,
      },
      {
        path: 'parameters.d.ts',
        contents: expect.stringContaining(
          '  export const parameters: {\n    readonly bypass: Parameter<boolean, { readonly id: "bypass"; readonly label: "Bypass"; readonly type: "bool"; readonly default: false }>;\n    readonly gain: Parameter<number, { readonly id: "gain"; readonly label: "Gain"; readonly type: "float"; readonly min: 0; readonly max: 1; readonly default: 0.5; readonly unit: "dB" }>;\n    readonly mode: Parameter<"mono" | "stereo", { readonly id: "mode"; readonly label: "Mode"; readonly type: "enum"; readonly values: readonly ["mono", "stereo"]; readonly default: "stereo" }>;\n    readonly voices: Parameter<number, { readonly id: "voices"; readonly label: "Voices"; readonly type: "int"; readonly min: 1; readonly max: 16; readonly default: 4 }>;\n  };',
        ),
      },
      {
        path: 'platform.d.ts',
        contents: expect.stringContaining(
          'export const plugin: { readonly id: "com.example.plugin"; readonly name: "Example" };',
        ),
      },
      {
        path: 'soundor.d.ts',
        contents: `// This file was generated by Soundor. Do not edit.

/// <reference path="./globals.d.ts" />
/// <reference path="./native.d.ts" />
/// <reference path="./parameters.d.ts" />
/// <reference path="./platform.d.ts" />
/// <reference path="./ui.d.ts" />
`,
      },
      {
        path: 'ui.d.ts',
        contents: expect.stringContaining("declare module 'soundor:ui' {"),
      },
    ]);
  });

  it('produces the same bytes for semantically identical orderings', () => {
    const reversed: CoreSoundorConfig = {
      plugin: config.plugin,
      parameters: [...config.parameters].reverse(),
      native: {
        methods: { reset: {}, measure: config.native!.methods!['measure']! },
        types: config.native!.types!,
      },
    };

    expect(generateSoundorFiles(reversed)).toEqual(
      generateSoundorFiles(config),
    );
  });
});

describe('generated file writer', () => {
  let root: string;
  let fs: FileSystemHost;
  let outputDir: string;

  beforeEach(async () => {
    root = await mkdtemp(join(tmpdir(), 'soundor-generate-'));
    fs = createNodeFileSystem(root);
    outputDir = fs.resolve('.soundor', 'generated');
  });

  afterEach(async () => {
    await rm(root, { recursive: true, force: true });
  });

  it('writes generated files idempotently', async () => {
    const files = generateSoundorFiles(config);

    await writeGeneratedFiles(fs, outputDir, files);
    const first = await fs.read(join(outputDir, 'parameters.d.ts'));

    await writeGeneratedFiles(fs, outputDir, files);

    expect(await fs.read(join(outputDir, 'parameters.d.ts'))).toBe(first);
    await expect(checkGeneratedFiles(fs, outputDir, files)).resolves.toEqual([
      { path: 'globals.d.ts', status: 'up-to-date' },
      { path: 'native.d.ts', status: 'up-to-date' },
      { path: 'parameters.d.ts', status: 'up-to-date' },
      { path: 'platform.d.ts', status: 'up-to-date' },
      { path: 'soundor.d.ts', status: 'up-to-date' },
      { path: 'ui.d.ts', status: 'up-to-date' },
    ]);
  });

  it('resolves relative output dirs through the filesystem host', async () => {
    const files = generateSoundorFiles(config);

    await writeGeneratedFiles(fs, '.soundor/generated', files);

    await expect(
      fs.read(join(root, '.soundor', 'generated', 'parameters.d.ts')),
    ).resolves.toContain("declare module 'soundor:parameters'");
  });

  it('reports missing and stale generated files in check mode', async () => {
    const files = generateSoundorFiles(config);
    await writeGeneratedFiles(fs, outputDir, files);
    await fs.write(join(outputDir, 'parameters.d.ts'), 'stale');
    await fs.rm(join(outputDir, 'native.d.ts'));

    await expect(
      checkGeneratedFiles(fs, outputDir, files),
    ).rejects.toMatchObject({
      changes: [
        { path: 'native.d.ts', kind: 'missing' },
        { path: 'parameters.d.ts', kind: 'stale' },
      ],
    } satisfies Partial<GeneratedFilesOutOfDateError>);
  });

  it('rejects unsafe generated file paths', async () => {
    await expect(
      writeGeneratedFiles(fs, outputDir, [
        { path: '../user.ts', contents: '' },
      ]),
    ).rejects.toThrow('Unsafe generated file path');
  });
});
