import { resolve as resolvePath, sep } from 'node:path';

import type { CodegenFile } from './codegen';
import { SoundorError } from './errors';
import type { FileSystemHost } from './filesystem';
import { renderGlobalsDts } from './globals-dts';
import { describeNativeApi, type NativeApiDeclaration } from './native-api';
import { renderNativeDts } from './native-dts';
import { renderParametersDts } from './parameters-dts';
import { renderPlatformDts } from './platform-dts';
import { renderUiDts } from './ui-dts';

const HEADER = '// This file was generated by Soundor. Do not edit.\n\n';

export interface CoreRuntimeDescriptor {
  readonly id: string;
}

export interface CoreBaseParameter {
  readonly id: string;
  readonly label: string;
}

export interface CoreFloatParameter extends CoreBaseParameter {
  readonly type: 'float';
  readonly min: number;
  readonly max: number;
  readonly default: number;
  readonly unit?: string;
}

export interface CoreIntParameter extends CoreBaseParameter {
  readonly type: 'int';
  readonly min: number;
  readonly max: number;
  readonly default: number;
  readonly unit?: string;
}

export interface CoreBoolParameter extends CoreBaseParameter {
  readonly type: 'bool';
  readonly default: boolean;
}

export interface CoreEnumParameter extends CoreBaseParameter {
  readonly type: 'enum';
  readonly values: readonly string[];
  readonly default: string;
}

export type CoreParameter =
  | CoreFloatParameter
  | CoreIntParameter
  | CoreBoolParameter
  | CoreEnumParameter;

export interface CorePluginIdentity {
  readonly id: string;
  readonly name: string;
}

export interface CoreSoundorConfig {
  readonly plugin: CorePluginIdentity;
  readonly runtimes?: readonly CoreRuntimeDescriptor[];
  readonly parameters: readonly CoreParameter[];
  readonly native?: NativeApiDeclaration;
}

export interface GeneratedFileChange {
  readonly path: string;
  readonly kind: 'missing' | 'stale';
}

export interface GeneratedFileWriteResult {
  readonly path: string;
  readonly status: 'created' | 'updated' | 'unchanged';
}

export interface GeneratedFileCheckResult {
  readonly path: string;
  readonly status: 'up-to-date';
}

export class GeneratedFilesOutOfDateError extends SoundorError {
  readonly changes: GeneratedFileChange[];

  constructor(changes: readonly GeneratedFileChange[]) {
    super(
      `Generated files are out of date: ${changes.map((change) => change.path).join(', ')}.`,
      {
        code: 'CONFIG',
        issues: changes.map((change) => ({
          path: change.path,
          message:
            change.kind === 'missing'
              ? 'generated file is missing'
              : 'generated file contents are stale',
        })),
      },
    );
    this.name = 'GeneratedFilesOutOfDateError';
    this.changes = [...changes];
  }
}

export function generateSoundorFiles(config: CoreSoundorConfig): CodegenFile[] {
  return [
    { path: 'globals.d.ts', contents: renderGlobalsDts() },
    { path: 'native.d.ts', contents: renderNativeDts(nativeApiModel(config)) },
    {
      path: 'parameters.d.ts',
      contents: renderParametersDts(config.parameters),
    },
    { path: 'platform.d.ts', contents: renderPlatformDts(config.plugin) },
    { path: 'soundor.d.ts', contents: renderSoundorDts() },
    { path: 'ui.d.ts', contents: renderUiDts() },
  ];
}

export async function writeGeneratedFiles(
  fs: FileSystemHost,
  outputDir: string,
  files: readonly CodegenFile[],
): Promise<GeneratedFileWriteResult[]> {
  const results: GeneratedFileWriteResult[] = [];
  for (const file of sortFiles(files)) {
    const target = generatedTarget(fs, outputDir, file.path);
    const exists = await fs.exists(target);
    if (exists && (await fs.read(target)) === file.contents) {
      results.push({ path: file.path, status: 'unchanged' });
      continue;
    }
    await fs.write(target, file.contents);
    results.push({ path: file.path, status: exists ? 'updated' : 'created' });
  }
  return results;
}

export async function checkGeneratedFiles(
  fs: FileSystemHost,
  outputDir: string,
  files: readonly CodegenFile[],
): Promise<GeneratedFileCheckResult[]> {
  const changes: GeneratedFileChange[] = [];
  const sorted = sortFiles(files);
  for (const file of sorted) {
    const target = generatedTarget(fs, outputDir, file.path);
    if (!(await fs.exists(target))) {
      changes.push({ path: file.path, kind: 'missing' });
      continue;
    }
    if ((await fs.read(target)) !== file.contents) {
      changes.push({ path: file.path, kind: 'stale' });
    }
  }
  if (changes.length > 0) throw new GeneratedFilesOutOfDateError(changes);
  return sorted.map((file) => ({ path: file.path, status: 'up-to-date' }));
}

/** The resolved native API; config validation has already rejected bad input. */
function nativeApiModel(config: CoreSoundorConfig) {
  const result = describeNativeApi(config.native);
  if (!result.ok) {
    throw new SoundorError('Invalid native API declaration.', {
      code: 'CONFIG',
      issues: [...result.issues],
    });
  }
  return result.model;
}

/**
 * The one declaration file a project registers (tsconfig `types`): it pulls in
 * the declarations of the runtime-provided `soundor:*` modules generated from
 * the config.
 */
function renderSoundorDts(): string {
  return `${HEADER}/// <reference path="./globals.d.ts" />\n/// <reference path="./native.d.ts" />\n/// <reference path="./parameters.d.ts" />\n/// <reference path="./platform.d.ts" />\n/// <reference path="./ui.d.ts" />\n`;
}

function sortFiles(files: readonly CodegenFile[]): CodegenFile[] {
  return [...files].sort((a, b) => a.path.localeCompare(b.path));
}

function generatedTarget(
  fs: FileSystemHost,
  outputDir: string,
  filePath: string,
): string {
  if (filePath.startsWith('/') || filePath.includes('\\')) {
    throw new SoundorError(`Unsafe generated file path: ${filePath}`, {
      code: 'INTERNAL',
    });
  }

  const base = fs.resolve(outputDir);
  const target = resolvePath(base, filePath);
  if (target !== base && !target.startsWith(`${base}${sep}`)) {
    throw new SoundorError(`Unsafe generated file path: ${filePath}`, {
      code: 'INTERNAL',
    });
  }
  return target;
}
