import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { createNodeFileSystem, type FileSystemHost } from './filesystem';
import {
  GeneratedFilesOutOfDateError,
  checkGeneratedFiles,
  generateSoundorFiles,
  writeGeneratedFiles,
  type CoreSoundorConfig,
} from './generate';

const config: CoreSoundorConfig = {
  runtimes: [{ id: 'juce' }],
  parameters: [
    { type: 'bool', id: 'bypass', label: 'Bypass', default: false },
    {
      type: 'float',
      id: 'gain',
      label: 'Gain',
      min: 0,
      max: 1,
      default: 0.5,
      unit: 'dB',
    },
    {
      type: 'enum',
      id: 'mode',
      label: 'Mode',
      values: ['mono', 'stereo'],
      default: 'stereo',
    },
    { type: 'int', id: 'voices', label: 'Voices', min: 1, max: 16, default: 4 },
  ],
  nativeMethods: [
    { name: 'render', input: 'RenderRequest', output: 'RenderResult' },
  ],
};

describe('generateSoundorFiles', () => {
  it('emits deterministic golden files', () => {
    expect(generateSoundorFiles(config)).toEqual([
      {
        path: 'parameters.ts',
        contents: `// This file was generated by Soundor. Do not edit.

export const parameters = {
  bypass: { default: false, id: "bypass", label: "Bypass", type: "bool" },
  gain: { default: 0.5, id: "gain", label: "Gain", max: 1, min: 0, type: "float", unit: "dB" },
  mode: { default: "stereo", id: "mode", label: "Mode", type: "enum", values: ["mono", "stereo"] },
  voices: { default: 4, id: "voices", label: "Voices", max: 16, min: 1, type: "int" },
} as const;

export type ParameterId = keyof typeof parameters;

export type ParameterInfoMap = typeof parameters;

export type ParameterValueMap = {
  bypass: boolean;
  gain: number;
  mode: "mono" | "stereo";
  voices: number;
};

export type ParameterValue<T extends ParameterId> = ParameterValueMap[T];

export const useParamInfo = parameters;

declare module '@soundor/bridge' {
  interface SoundorParamInfoMap extends ParameterInfoMap {}
  interface SoundorParamValueMap extends ParameterValueMap {}
}
`,
      },
      {
        path: 'parameters.json',
        contents: `{
  "parameters": [
    {
      "default": false,
      "id": "bypass",
      "label": "Bypass",
      "type": "bool"
    },
    {
      "default": 0.5,
      "id": "gain",
      "label": "Gain",
      "max": 1,
      "min": 0,
      "type": "float",
      "unit": "dB"
    },
    {
      "default": "stereo",
      "id": "mode",
      "label": "Mode",
      "type": "enum",
      "values": [
        "mono",
        "stereo"
      ]
    },
    {
      "default": 4,
      "id": "voices",
      "label": "Voices",
      "max": 16,
      "min": 1,
      "type": "int"
    }
  ]
}
`,
      },
      {
        path: 'native-methods.ts',
        contents: `// This file was generated by Soundor. Do not edit.

export type RenderRequest = unknown;
export type RenderResult = unknown;

export interface NativeMethodRequests {
  render: RenderRequest;
}

export interface NativeMethodResponses {
  render: RenderResult;
}

export type NativeMethodName = keyof NativeMethodRequests;

export type NativeMethodDispatcher = {
  [K in NativeMethodName]: (
    request: NativeMethodRequests[K],
  ) => Promise<NativeMethodResponses[K]>;
};

declare module '@soundor/bridge' {
  interface SoundorNativeMethodRequests extends NativeMethodRequests {}
  interface SoundorNativeMethodResponses extends NativeMethodResponses {}
}
`,
      },
    ]);
  });

  it('produces the same bytes for semantically identical orderings', () => {
    const reversed: CoreSoundorConfig = {
      parameters: [...config.parameters].reverse(),
      nativeMethods: [...(config.nativeMethods ?? [])].reverse(),
    };

    expect(generateSoundorFiles(reversed)).toEqual(
      generateSoundorFiles(config),
    );
  });
});

describe('generated file writer', () => {
  let root: string;
  let fs: FileSystemHost;
  let outputDir: string;

  beforeEach(async () => {
    root = await mkdtemp(join(tmpdir(), 'soundor-generate-'));
    fs = createNodeFileSystem(root);
    outputDir = fs.resolve('.soundor', 'generated');
  });

  afterEach(async () => {
    await rm(root, { recursive: true, force: true });
  });

  it('writes generated files idempotently', async () => {
    const files = generateSoundorFiles(config);

    await writeGeneratedFiles(fs, outputDir, files);
    const first = await fs.read(join(outputDir, 'parameters.ts'));

    await writeGeneratedFiles(fs, outputDir, files);

    expect(await fs.read(join(outputDir, 'parameters.ts'))).toBe(first);
    await expect(
      checkGeneratedFiles(fs, outputDir, files),
    ).resolves.toBeUndefined();
  });

  it('resolves relative output dirs through the filesystem host', async () => {
    const files = generateSoundorFiles(config);

    await writeGeneratedFiles(fs, '.soundor/generated', files);

    await expect(
      fs.read(join(root, '.soundor', 'generated', 'parameters.ts')),
    ).resolves.toContain('export type ParameterId');
  });

  it('reports missing and stale generated files in check mode', async () => {
    const files = generateSoundorFiles(config);
    await writeGeneratedFiles(fs, outputDir, files);
    await fs.write(join(outputDir, 'parameters.ts'), 'stale');
    await fs.rm(join(outputDir, 'parameters.json'));

    await expect(
      checkGeneratedFiles(fs, outputDir, files),
    ).rejects.toMatchObject({
      changes: [
        { path: 'parameters.json', kind: 'missing' },
        { path: 'parameters.ts', kind: 'stale' },
      ],
    } satisfies Partial<GeneratedFilesOutOfDateError>);
  });

  it('rejects unsafe generated file paths', async () => {
    await expect(
      writeGeneratedFiles(fs, outputDir, [
        { path: '../user.ts', contents: '' },
      ]),
    ).rejects.toThrow('Unsafe generated file path');
  });
});
