/**
 * The global types of Soundor's JavaScript runtime: exactly the Web subset it
 * provides, and image imports. A plugin's tsconfig uses `lib: ["ES2023"]`
 * without "DOM", so code touching `window` or `document` fails to compile
 * instead of failing in the plugin.
 */

const HEADER = '// This file was generated by Soundor. Do not edit.\n\n';

const GLOBALS = `// ── Assets ──────────────────────────────────────────────────────────────────

/** A bundled image: its stable id, resolved by Soundor's renderer. */
type SoundorAsset = string & { readonly __soundorAsset: true };

declare module '*.png' {
  const asset: SoundorAsset;
  export default asset;
}
declare module '*.jpg' {
  const asset: SoundorAsset;
  export default asset;
}
declare module '*.jpeg' {
  const asset: SoundorAsset;
  export default asset;
}
declare module '*.webp' {
  const asset: SoundorAsset;
  export default asset;
}

// ── Global scope ─────────────────────────────────────────────────────────────

declare var self: typeof globalThis;

interface Console {
  log(...data: unknown[]): void;
  info(...data: unknown[]): void;
  debug(...data: unknown[]): void;
  warn(...data: unknown[]): void;
  error(...data: unknown[]): void;
  trace(...data: unknown[]): void;
  assert(condition?: boolean, ...data: unknown[]): void;
  dir(item?: unknown): void;
  table(...data: unknown[]): void;
  group(...label: unknown[]): void;
  groupCollapsed(...label: unknown[]): void;
  groupEnd(): void;
  count(label?: string): void;
  countReset(label?: string): void;
  time(label?: string): void;
  timeLog(label?: string, ...data: unknown[]): void;
  timeEnd(label?: string): void;
}
declare var console: Console;

declare function setTimeout(handler: (...args: any[]) => void, timeout?: number, ...args: any[]): number;
declare function clearTimeout(id: number | undefined): void;
declare function setInterval(handler: (...args: any[]) => void, timeout?: number, ...args: any[]): number;
declare function clearInterval(id: number | undefined): void;
declare function queueMicrotask(callback: () => void): void;
/** Runs \`callback\` once, on the plugin view's next frame, before it is drawn. */
declare function requestAnimationFrame(callback: (time: number) => void): number;
declare function cancelAnimationFrame(id: number): void;
declare function reportError(error: unknown): void;
declare function structuredClone<T>(value: T, options?: { transfer?: ArrayBuffer[] }): T;
declare function atob(data: string): string;
declare function btoa(data: string): string;

declare var performance: {
  now(): number;
  readonly timeOrigin: number;
  toJSON(): { timeOrigin: number };
};

declare var crypto: {
  getRandomValues<T extends Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | BigInt64Array | BigUint64Array>(array: T): T;
  randomUUID(): \`\${string}-\${string}-\${string}-\${string}-\${string}\`;
};

// ── Errors ───────────────────────────────────────────────────────────────────

interface DOMException extends Error {
  readonly code: number;
}
declare var DOMException: {
  prototype: DOMException;
  new (message?: string, name?: string): DOMException;
};

// ── Events ───────────────────────────────────────────────────────────────────

interface EventInit {
  bubbles?: boolean;
  cancelable?: boolean;
  composed?: boolean;
}
interface Event {
  readonly type: string;
  readonly bubbles: boolean;
  readonly cancelable: boolean;
  readonly composed: boolean;
  readonly defaultPrevented: boolean;
  readonly target: EventTarget | null;
  readonly currentTarget: EventTarget | null;
  readonly eventPhase: number;
  readonly timeStamp: number;
  readonly isTrusted: boolean;
  composedPath(): EventTarget[];
  preventDefault(): void;
  stopPropagation(): void;
  stopImmediatePropagation(): void;
}
declare var Event: {
  prototype: Event;
  new (type: string, eventInitDict?: EventInit): Event;
  readonly NONE: 0;
  readonly CAPTURING_PHASE: 1;
  readonly AT_TARGET: 2;
  readonly BUBBLING_PHASE: 3;
};

interface CustomEventInit<T = unknown> extends EventInit {
  detail?: T;
}
interface CustomEvent<T = unknown> extends Event {
  readonly detail: T;
}
declare var CustomEvent: {
  prototype: CustomEvent;
  new <T>(type: string, eventInitDict?: CustomEventInit<T>): CustomEvent<T>;
};

type EventListenerOrEventListenerObject = ((event: Event) => void) | { handleEvent(event: Event): void };
interface AddEventListenerOptions {
  capture?: boolean;
  once?: boolean;
  passive?: boolean;
  signal?: AbortSignal;
}
interface EventTarget {
  addEventListener(type: string, listener: EventListenerOrEventListenerObject | null, options?: boolean | AddEventListenerOptions): void;
  removeEventListener(type: string, listener: EventListenerOrEventListenerObject | null, options?: boolean | { capture?: boolean }): void;
  dispatchEvent(event: Event): boolean;
}
declare var EventTarget: {
  prototype: EventTarget;
  new (): EventTarget;
};

interface AbortSignal extends EventTarget {
  readonly aborted: boolean;
  readonly reason: any;
  onabort: ((this: AbortSignal, event: Event) => any) | null;
  throwIfAborted(): void;
}
declare var AbortSignal: {
  prototype: AbortSignal;
  abort(reason?: any): AbortSignal;
  timeout(milliseconds: number): AbortSignal;
  any(signals: Iterable<AbortSignal>): AbortSignal;
};
interface AbortController {
  readonly signal: AbortSignal;
  abort(reason?: any): void;
}
declare var AbortController: {
  prototype: AbortController;
  new (): AbortController;
};

// ── Encoding ─────────────────────────────────────────────────────────────────

type BufferSource = ArrayBufferView | ArrayBuffer;

interface TextEncoder {
  readonly encoding: 'utf-8';
  encode(input?: string): Uint8Array;
  encodeInto(source: string, destination: Uint8Array): { read: number; written: number };
}
declare var TextEncoder: {
  prototype: TextEncoder;
  new (): TextEncoder;
};
interface TextDecoder {
  readonly encoding: 'utf-8';
  readonly fatal: boolean;
  readonly ignoreBOM: boolean;
  decode(input?: BufferSource, options?: { stream?: boolean }): string;
}
declare var TextDecoder: {
  prototype: TextDecoder;
  /** Soundor decodes UTF-8 only. */
  new (label?: 'utf-8' | 'utf8' | 'unicode-1-1-utf-8', options?: { fatal?: boolean; ignoreBOM?: boolean }): TextDecoder;
};

// ── URL ──────────────────────────────────────────────────────────────────────

interface URL {
  href: string;
  readonly origin: string;
  protocol: string;
  username: string;
  password: string;
  host: string;
  hostname: string;
  port: string;
  pathname: string;
  search: string;
  readonly searchParams: URLSearchParams;
  hash: string;
  toString(): string;
  toJSON(): string;
}
declare var URL: {
  prototype: URL;
  new (url: string | URL, base?: string | URL): URL;
  canParse(url: string | URL, base?: string | URL): boolean;
  parse(url: string | URL, base?: string | URL): URL | null;
};

interface URLSearchParams {
  readonly size: number;
  append(name: string, value: string): void;
  delete(name: string, value?: string): void;
  get(name: string): string | null;
  getAll(name: string): string[];
  has(name: string, value?: string): boolean;
  set(name: string, value: string): void;
  sort(): void;
  forEach(callback: (value: string, key: string, parent: URLSearchParams) => void, thisArg?: any): void;
  entries(): IterableIterator<[string, string]>;
  keys(): IterableIterator<string>;
  values(): IterableIterator<string>;
  [Symbol.iterator](): IterableIterator<[string, string]>;
  toString(): string;
}
declare var URLSearchParams: {
  prototype: URLSearchParams;
  new (init?: string[][] | Record<string, string> | string | URLSearchParams): URLSearchParams;
};

// ── Blob, File, FormData ─────────────────────────────────────────────────────

type BlobPart = BufferSource | Blob | string;
interface Blob {
  readonly size: number;
  readonly type: string;
  arrayBuffer(): Promise<ArrayBuffer>;
  bytes(): Promise<Uint8Array>;
  text(): Promise<string>;
  slice(start?: number, end?: number, contentType?: string): Blob;
}
declare var Blob: {
  prototype: Blob;
  new (blobParts?: BlobPart[], options?: { type?: string }): Blob;
};
interface File extends Blob {
  readonly name: string;
  readonly lastModified: number;
}
declare var File: {
  prototype: File;
  new (fileBits: BlobPart[], fileName: string, options?: { type?: string; lastModified?: number }): File;
};

type FormDataEntryValue = File | string;
interface FormData {
  append(name: string, value: string | Blob, fileName?: string): void;
  delete(name: string): void;
  get(name: string): FormDataEntryValue | null;
  getAll(name: string): FormDataEntryValue[];
  has(name: string): boolean;
  set(name: string, value: string | Blob, fileName?: string): void;
  forEach(callback: (value: FormDataEntryValue, key: string, parent: FormData) => void, thisArg?: any): void;
  entries(): IterableIterator<[string, FormDataEntryValue]>;
  keys(): IterableIterator<string>;
  values(): IterableIterator<FormDataEntryValue>;
  [Symbol.iterator](): IterableIterator<[string, FormDataEntryValue]>;
}
declare var FormData: {
  prototype: FormData;
  new (): FormData;
};

// ── Fetch ────────────────────────────────────────────────────────────────────

type HeadersInit = [string, string][] | Record<string, string> | Headers;
interface Headers {
  append(name: string, value: string): void;
  delete(name: string): void;
  get(name: string): string | null;
  getSetCookie(): string[];
  has(name: string): boolean;
  set(name: string, value: string): void;
  forEach(callback: (value: string, key: string, parent: Headers) => void, thisArg?: any): void;
  entries(): IterableIterator<[string, string]>;
  keys(): IterableIterator<string>;
  values(): IterableIterator<string>;
  [Symbol.iterator](): IterableIterator<[string, string]>;
}
declare var Headers: {
  prototype: Headers;
  new (init?: HeadersInit): Headers;
};

/** Bodies are buffered: Soundor has no Web Streams, so there is no \`body\` stream. */
interface Body {
  readonly bodyUsed: boolean;
  arrayBuffer(): Promise<ArrayBuffer>;
  bytes(): Promise<Uint8Array>;
  blob(): Promise<Blob>;
  formData(): Promise<FormData>;
  json(): Promise<any>;
  text(): Promise<string>;
}
type BodyInit = Blob | BufferSource | FormData | URLSearchParams | string;
interface RequestInit {
  method?: string;
  headers?: HeadersInit;
  body?: BodyInit | null;
  signal?: AbortSignal | null;
  /** Only "follow" is supported. */
  redirect?: 'follow';
}
interface Request extends Body {
  readonly method: string;
  readonly url: string;
  readonly headers: Headers;
  readonly signal: AbortSignal;
  readonly redirect: 'follow' | 'error' | 'manual';
  clone(): Request;
}
declare var Request: {
  prototype: Request;
  new (input: string | URL | Request, init?: RequestInit): Request;
};
interface ResponseInit {
  status?: number;
  statusText?: string;
  headers?: HeadersInit;
}
interface Response extends Body {
  readonly status: number;
  readonly statusText: string;
  readonly ok: boolean;
  readonly headers: Headers;
  readonly url: string;
  readonly redirected: boolean;
  readonly type: 'basic' | 'default' | 'error';
  clone(): Response;
}
declare var Response: {
  prototype: Response;
  new (body?: BodyInit | null, init?: ResponseInit): Response;
  error(): Response;
  json(data: unknown, init?: ResponseInit): Response;
  redirect(url: string | URL, status?: number): Response;
};
declare function fetch(input: string | URL | Request, init?: RequestInit): Promise<Response>;
`;

export function renderGlobalsDts(): string {
  return `${HEADER}${GLOBALS}`;
}
