/**
 * Renders the TypeScript declaration of the runtime-provided `soundor:native`
 * module from a {@link NativeApiModel}. The file is an ambient module
 * declaration: plugin code imports from `'soundor:native'` and the bundler
 * leaves the import for the runtime to resolve.
 */

import type { NativeApiModel, NativeType, NativeTypeModel } from './native-api';

const HEADER = '// This file was generated by Soundor. Do not edit.\n\n';

export function renderNativeDts(model: NativeApiModel): string {
  const blocks = [
    ...model.types.map(renderType),
    ...model.methods.map((method) => {
      const args = method.args
        .map((arg) => `${arg.name}: ${tsType(arg.type, 'argument')}`)
        .join(', ');
      const result = tsType(method.returns, 'result');
      return `  export function ${method.name}(${args}): ${method.async ? `Promise<${result}>` : result};`;
    }),
  ];
  const body = blocks.length > 0 ? `\n${blocks.join('\n\n')}\n` : '\n';
  return `${HEADER}declare module 'soundor:native' {${body}}\n`;
}

function renderType(type: NativeTypeModel): string {
  switch (type.kind) {
    case 'handle':
      return [
        `  /** An opaque reference to a native ${type.name}. Only native methods can create one. */`,
        `  export interface ${type.name} {`,
        `    readonly __soundorHandle: '${type.name}';`,
        '  }',
      ].join('\n');
    case 'enum':
      return `  export type ${type.name} = ${type.values.map((value) => JSON.stringify(value)).join(' | ')};`;
    case 'struct': {
      const fields = type.fields.map(
        (field) => `    ${field.name}: ${tsType(field.type, 'result')};`,
      );
      return [`  export interface ${type.name} {`, ...fields, '  }'].join('\n');
    }
  }
}

/** Arguments accept readonly arrays; results hand out mutable copies. */
function tsType(type: NativeType, position: 'argument' | 'result'): string {
  switch (type.kind) {
    case 'void':
      return 'void';
    case 'primitive':
    case 'binary':
    case 'declared':
      return type.name;
    case 'array': {
      const element = tsType(type.element, position);
      return position === 'argument' ? `readonly ${element}[]` : `${element}[]`;
    }
  }
}
