/**
 * Renders the TypeScript declaration of the runtime-provided
 * `soundor:parameters` module from the config's parameters. Every parameter is
 * a typed {@link Parameter} whose `info` keeps the exact literal metadata
 * (ids, ranges, enum values) so UI code can rely on it.
 */

import type { CoreParameter } from './generate';

const HEADER = '// This file was generated by Soundor. Do not edit.\n\n';

const PRELUDE = `  /** Metadata of a parameter, as declared in soundor.config. */
  export type ParameterInfo =
    | {
        readonly id: string;
        readonly label: string;
        readonly type: 'float' | 'int';
        readonly min: number;
        readonly max: number;
        readonly default: number;
        readonly unit?: string;
      }
    | {
        readonly id: string;
        readonly label: string;
        readonly type: 'bool';
        readonly default: boolean;
      }
    | {
        readonly id: string;
        readonly label: string;
        readonly type: 'enum';
        readonly values: readonly string[];
        readonly default: string;
      };

  /**
   * A plugin parameter, shared with the DSP and the host. Values are in plain
   * units: numbers within [min, max], booleans, or one of an enum's values.
   */
  export interface Parameter<Value, Info extends ParameterInfo = ParameterInfo> {
    readonly id: Info['id'];
    readonly info: Info;
    /** The current value. */
    get(): Value;
    /** Sets the value (numbers are clamped to the range, ints rounded) and notifies the host. */
    set(value: Value): void;
    /**
     * Calls \`listener\` with the new value after every change, from any source:
     * the UI, host automation, or a preset. Returns a function that unsubscribes.
     */
    subscribe(listener: (value: Value) => void): () => void;
    /** Starts a user interaction (e.g. a drag); the host records the changes until endGesture() as one gesture. */
    beginGesture(): void;
    /** Ends the interaction started with beginGesture(). */
    endGesture(): void;
  }`;

export function renderParametersDts(
  parameters: readonly CoreParameter[],
): string {
  const entries = [...parameters]
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))
    .map(
      (parameter) =>
        `    readonly ${propertyKey(parameter.id)}: Parameter<${valueType(parameter)}, ${infoType(parameter)}>;`,
    );
  const map =
    entries.length > 0
      ? `{\n${entries.join('\n')}\n  }`
      : 'Record<never, never>';
  return `${HEADER}declare module 'soundor:parameters' {
${PRELUDE}

  /** Every parameter declared in soundor.config, by id. */
  export const parameters: ${map};
}
`;
}

function valueType(parameter: CoreParameter): string {
  switch (parameter.type) {
    case 'float':
    case 'int':
      return 'number';
    case 'bool':
      return 'boolean';
    case 'enum':
      return parameter.values.map((value) => JSON.stringify(value)).join(' | ');
  }
}

function infoType(parameter: CoreParameter): string {
  const fields: [string, string][] = [
    ['id', JSON.stringify(parameter.id)],
    ['label', JSON.stringify(parameter.label)],
    ['type', JSON.stringify(parameter.type)],
  ];
  switch (parameter.type) {
    case 'float':
    case 'int':
      fields.push(
        ['min', String(parameter.min)],
        ['max', String(parameter.max)],
        ['default', String(parameter.default)],
      );
      if (parameter.unit !== undefined) {
        fields.push(['unit', JSON.stringify(parameter.unit)]);
      }
      break;
    case 'bool':
      fields.push(['default', String(parameter.default)]);
      break;
    case 'enum':
      fields.push(
        [
          'values',
          `readonly [${parameter.values.map((value) => JSON.stringify(value)).join(', ')}]`,
        ],
        ['default', JSON.stringify(parameter.default)],
      );
      break;
  }
  return `{ ${fields.map(([key, type]) => `readonly ${key}: ${type}`).join('; ')} }`;
}

function propertyKey(id: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(id) ? id : JSON.stringify(id);
}
