/**
 * Renders the declaration of the runtime-provided `soundor:ui` module: the
 * plugin view's node tree, its flexbox style and its input events. The same
 * for every project.
 */

const HEADER = '// This file was generated by Soundor. Do not edit.\n\n';

const UI = `declare module 'soundor:ui' {
  /** Logical pixels, a percentage of the parent, or (where allowed) 'auto'. */
  export type Dimension = number | \`\${number}%\` | 'auto';
  export type Percentage = number | \`\${number}%\`;
  export type FlexAlign =
    | 'auto'
    | 'flex-start'
    | 'center'
    | 'flex-end'
    | 'stretch'
    | 'baseline'
    | 'space-between'
    | 'space-around'
    | 'space-evenly';

  /**
   * Flexbox layout as in React Native (column by default, no shrinking unless
   * asked) and text properties.
   */
  export interface Style {
    display?: 'flex' | 'none';
    position?: 'relative' | 'absolute' | 'static';
    flexDirection?: 'column' | 'column-reverse' | 'row' | 'row-reverse';
    flexWrap?: 'nowrap' | 'wrap' | 'wrap-reverse';
    justifyContent?:
      | 'flex-start'
      | 'center'
      | 'flex-end'
      | 'space-between'
      | 'space-around'
      | 'space-evenly';
    alignItems?: FlexAlign;
    alignSelf?: FlexAlign;
    alignContent?: FlexAlign;
    /** \`flex: n\` (n > 0) grows by n, shrinks, and starts from zero. */
    flex?: number;
    flexGrow?: number;
    flexShrink?: number;
    flexBasis?: Dimension;

    width?: Dimension;
    height?: Dimension;
    minWidth?: Percentage;
    minHeight?: Percentage;
    maxWidth?: Percentage;
    maxHeight?: Percentage;
    aspectRatio?: number;
    boxSizing?: 'border-box' | 'content-box';

    margin?: Dimension;
    marginHorizontal?: Dimension;
    marginVertical?: Dimension;
    marginTop?: Dimension;
    marginRight?: Dimension;
    marginBottom?: Dimension;
    marginLeft?: Dimension;
    padding?: Percentage;
    paddingHorizontal?: Percentage;
    paddingVertical?: Percentage;
    paddingTop?: Percentage;
    paddingRight?: Percentage;
    paddingBottom?: Percentage;
    paddingLeft?: Percentage;
    borderWidth?: number;
    borderHorizontalWidth?: number;
    borderVerticalWidth?: number;
    borderTopWidth?: number;
    borderRightWidth?: number;
    borderBottomWidth?: number;
    borderLeftWidth?: number;
    inset?: Dimension;
    top?: Dimension;
    right?: Dimension;
    bottom?: Dimension;
    left?: Dimension;
    gap?: number;
    rowGap?: number;
    columnGap?: number;

    overflow?: 'visible' | 'hidden' | 'scroll';
    /** 'box-none': not the node, but its children; 'box-only': the reverse. */
    pointerEvents?: 'auto' | 'none' | 'box-none' | 'box-only';
    /**
     * An integer that stacks the node among its siblings: higher ones are
     * drawn over, and hit before, lower ones; equal ones keep tree order (the
     * later sibling on top). Not layout: flex order stays the tree's. 0 by
     * default.
     */
    zIndex?: number;

    fontFamily?: string;
    fontSize?: number;
    fontWeight?: number | 'normal' | 'bold';
    fontStyle?: 'normal' | 'italic';
    lineHeight?: number;
    letterSpacing?: number;
    textAlign?: 'auto' | 'left' | 'center' | 'right';
    /** Text nodes: at most this many lines (0: no limit). */
    numberOfLines?: number;
    color?: Color;

    /** Any CSS color: '#rgb[a]', '#rrggbb[aa]', rgb(), hsl(), a name, 'transparent'. */
    backgroundColor?: Color;
    borderColor?: Color;
    borderRadius?: number;
    borderTopLeftRadius?: number;
    borderTopRightRadius?: number;
    borderBottomRightRadius?: number;
    borderBottomLeftRadius?: number;
    /** 0 to 1, for the node and everything in it. */
    opacity?: number;
    /** Images: how the image fills the box. */
    resizeMode?: 'cover' | 'contain' | 'stretch' | 'center';
  }

  /** A CSS color string. */
  export type Color = string;

  export interface LayoutRect {
    readonly x: number;
    readonly y: number;
    readonly width: number;
    readonly height: number;
  }

  /**
   * What a node is to assistive technology (\`accessibilityRole\` in
   * @soundor/react). 'none': no role of its own.
   */
  export type AccessibilityRole =
    | 'none'
    | 'text'
    | 'image'
    | 'button'
    | 'link'
    | 'adjustable'
    | 'checkbox'
    | 'switch'
    | 'togglebutton'
    | 'radio'
    | 'radiogroup'
    | 'progressbar'
    | 'search'
    | 'combobox'
    | 'menu'
    | 'menubar'
    | 'menuitem'
    | 'scrollbar'
    | 'spinbutton'
    | 'tab'
    | 'tablist'
    | 'header'
    | 'summary'
    | 'keyboardkey'
    | 'timer'
    | 'toolbar'
    | 'alert'
    | 'dialog';

  export interface AccessibilityState {
    disabled?: boolean;
    selected?: boolean;
    /** 'mixed': partly checked. */
    checked?: boolean | 'mixed';
    busy?: boolean;
    expanded?: boolean;
  }

  /** A range's value (fractional values welcome), and how to read it. */
  export interface AccessibilityValue {
    min?: number;
    max?: number;
    now?: number;
    /** Read in place of the number: '-3.5 dB'. */
    text?: string;
  }

  /**
   * The actions the runtime knows; any other name is a custom action, offered
   * to the user by its label.
   */
  export type AccessibilityActionName =
    | 'activate'
    | 'increment'
    | 'decrement'
    | 'longpress'
    | 'expand'
    | 'collapse'
    | 'escape'
    | 'focus'
    | 'blur'
    | 'setValue'
    | (string & {});

  export interface AccessibilityAction {
    name: AccessibilityActionName;
    /** How a custom action is presented. */
    label?: string;
  }

  /**
   * What a node is to assistive technology (screen readers and the like).
   * The runtime fills in the rest from the node: its type, its text, whether
   * it is focusable, and where it is.
   */
  export interface Accessibility {
    /**
     * true: the node is an element assistive technology perceives; false: it
     * is not (its descendants still may be). By default, text nodes and
     * inputs are, and so is a node given a role or a label.
     */
    accessible?: boolean;
    role?: AccessibilityRole;
    label?: string;
    /** What happens when the element is acted on. */
    hint?: string;
    state?: AccessibilityState;
    value?: AccessibilityValue;
    /** The actions it responds to, as \`accessibilityaction\` events. */
    actions?: readonly AccessibilityAction[];
    /**
     * While shown, assistive technology perceives only this element and what
     * it holds (the last such element shown, when there are several).
     */
    modal?: boolean;
  }

  export interface UiEventMap {
    pointerdown: PointerEvent;
    pointermove: PointerEvent;
    pointerup: PointerEvent;
    pointercancel: PointerEvent;
    pointerenter: PointerEvent;
    pointerleave: PointerEvent;
    click: PointerEvent;
    /** The secondary button went down (or the platform's equivalent). */
    contextmenu: PointerEvent;
    wheel: WheelEvent;
    keydown: KeyboardEvent;
    keyup: KeyboardEvent;
    beforeinput: InputEvent;
    focus: FocusEvent;
    blur: FocusEvent;
    /** Scroll views: the content scrolled. */
    scroll: Event;
    /** Text inputs: the value changed. */
    input: InputEvent;
    /** Text inputs: the value was committed (Enter, or losing focus). */
    change: Event;
    /**
     * Assistive technology asks for an action. Bubbles; preventDefault()
     * says it was done, and keeps the runtime's own response (focusing, an
     * input's text) away.
     */
    accessibilityaction: AccessibilityActionEvent;
  }

  /**
   * A node of the view: a flexbox box ('view'), text, an image, a scroll view,
   * a text input or a canvas. Events capture and bubble along the tree as in
   * the DOM.
   */
  export class UiNode extends EventTarget {
    private constructor();
    readonly type: 'view' | 'text' | 'image' | 'scroll' | 'input' | 'canvas';
    readonly parent: UiNode | null;
    readonly children: readonly UiNode[];
    readonly firstChild: UiNode | null;
    readonly lastChild: UiNode | null;
    readonly nextSibling: UiNode | null;
    readonly previousSibling: UiNode | null;
    /** Whether the node is in the view's trees (under root or overlayRoot). */
    readonly isConnected: boolean;
    /** Replaced as a whole on assignment. */
    style: Readonly<Style>;
    /** Text nodes only. */
    text: string;
    /** What the node is to assistive technology; replaced as a whole on assignment. */
    accessibility: Readonly<Accessibility>;
    /**
     * Where assistive technology reads the node, in place of its parent
     * (null: its parent): content a portal shows away from where it belongs.
     */
    accessibilityParent: UiNode | null;
    /** Whether the node takes focus when pressed or tabbed to. */
    focusable: boolean;
    readonly focused: boolean;
    focus(): void;
    blur(): void;
    appendChild<T extends UiNode>(child: T): T;
    insertBefore<T extends UiNode>(child: T, before: UiNode | null): T;
    removeChild<T extends UiNode>(child: T): T;
    remove(): void;
    contains(other: UiNode | null): boolean;
    /** The laid-out box, relative to the parent's (scrolling aside). */
    readonly layout: LayoutRect;
    /**
     * The laid-out box relative to the view's top-left corner, where it shows
     * once its ancestors have scrolled. Zero when not connected.
     */
    getBoundingClientRect(): LayoutRect;

    /** Text inputs: the text. Setting it puts the caret at the end. */
    value: string;
    /** Text inputs: shown while empty. */
    placeholder: string;
    /** Text inputs: the selection, in UTF-16 indices (like the Web). */
    readonly selectionStart: number;
    readonly selectionEnd: number;
    readonly selectionDirection: 'forward' | 'backward';
    setSelectionRange(start: number, end: number, direction?: 'forward' | 'backward'): void;
    select(): void;

    /** Images: the bundled image shown (an imported asset). */
    source: SoundorAsset | '';

    /**
     * Canvases: the drawing buffer's size in pixels (300 by 150 to begin
     * with), shown stretched over the box. Setting either clears the canvas.
     */
    width: number;
    height: number;
    /**
     * Canvases: the drawing context, the same object every time; null for a
     * type the canvas cannot have (another than the one it has).
     */
    getContext(type: '2d', options?: CanvasRenderingContext2DSettings): CanvasRenderingContext2D | null;
    /** On the GPU; null where there is no acceptable GPU. */
    getContext(type: 'webgl2', options?: WebGLContextAttributes): WebGL2RenderingContext | null;
    getContext(type: string, options?: unknown): null;

    /** Scroll views: how far the content is scrolled, and its size. */
    scrollTop: number;
    scrollLeft: number;
    readonly scrollWidth: number;
    readonly scrollHeight: number;
    scrollTo(options: { top?: number; left?: number }): void;
    scrollTo(left: number, top: number): void;
    scrollBy(options: { top?: number; left?: number }): void;
    scrollBy(left: number, top: number): void;
    addEventListener<K extends keyof UiEventMap>(
      type: K,
      listener: (this: UiNode, event: UiEventMap[K]) => void,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject | null,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof UiEventMap>(
      type: K,
      listener: (this: UiNode, event: UiEventMap[K]) => void,
      options?: boolean | { capture?: boolean },
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject | null,
      options?: boolean | { capture?: boolean },
    ): void;
  }

  /** The view's root node; it always fills the view. */
  export const root: UiNode;
  /**
   * The view's overlay layer: a second root that fills the view, laid out
   * apart from root, drawn over root and everything in it (whatever their
   * zIndex) and hit before it. Where nothing in it takes pointer events,
   * they reach root. Events in it bubble up to it, not to root. Renderers
   * build overlays on it (@soundor/react's Portal).
   */
  export const overlayRoot: UiNode;
  export function createView(style?: Style): UiNode;
  export function createText(text?: string, style?: Style): UiNode;
  /** An image showing a bundled asset (\`import logo from './logo.png'\`). */
  export function createImage(source?: SoundorAsset, style?: Style): UiNode;
  /** A view whose children scroll (by wheel, or scrollTo()). */
  export function createScrollView(style?: Style): UiNode;
  /** A single-line text input; it is focusable and edits itself. */
  export function createTextInput(options?: { value?: string; placeholder?: string; style?: Style }): UiNode;
  /**
   * A canvas: pixels code draws with getContext('2d') or getContext('webgl2'). Its box is its
   * drawing buffer's size in logical pixels unless its style sizes it.
   */
  export function createCanvas(style?: Style): UiNode;

  // The canvas classes, which are globals too, as on the Web.
  export type CanvasRenderingContext2D = globalThis.CanvasRenderingContext2D;
  export const CanvasRenderingContext2D: typeof globalThis.CanvasRenderingContext2D;
  export type CanvasGradient = globalThis.CanvasGradient;
  export const CanvasGradient: typeof globalThis.CanvasGradient;
  export type CanvasPattern = globalThis.CanvasPattern;
  export const CanvasPattern: typeof globalThis.CanvasPattern;
  export type ImageData = globalThis.ImageData;
  export const ImageData: typeof globalThis.ImageData;
  export type TextMetrics = globalThis.TextMetrics;
  export const TextMetrics: typeof globalThis.TextMetrics;
  export type WebGL2RenderingContext = globalThis.WebGL2RenderingContext;
  export const WebGL2RenderingContext: typeof globalThis.WebGL2RenderingContext;

  export interface PressableState {
    readonly pressed: boolean;
    readonly hovered: boolean;
    readonly focused: boolean;
  }
  export interface PressableHandlers {
    /**
     * A click (primary button released over the node), Enter/Space while
     * focused, or assistive technology's 'activate'. Not after a long press,
     * when onLongPress is given.
     */
    onPress?: (event: PointerEvent | KeyboardEvent | AccessibilityActionEvent) => void;
    /**
     * The primary button stayed down \`delayLongPress\` ms, without moving
     * away (with the pointerdown event), or assistive technology's 'longpress'.
     */
    onLongPress?: (event: PointerEvent | AccessibilityActionEvent) => void;
    /** Milliseconds before a press is a long press: 500 by default. */
    delayLongPress?: number;
    onPressIn?: (event: PointerEvent) => void;
    onPressOut?: (event: PointerEvent) => void;
    onHoverIn?: (event: PointerEvent) => void;
    onHoverOut?: (event: PointerEvent) => void;
    onStateChange?: (state: PressableState) => void;
  }
  /** Makes a node pressable (and focusable); returns a function that undoes it. */
  export function pressable(node: UiNode, handlers?: PressableHandlers): () => void;

  /** The system clipboard's text. */
  export const clipboard: {
    readText(): Promise<string>;
    writeText(text: string): Promise<void>;
  };
  /** The node that has keyboard focus, if any. */
  export function focusedNode(): UiNode | null;
  /** The view's size in logical pixels, and device pixels per logical pixel. */
  export function viewSize(): { width: number; height: number; scale: number };

  interface ModifierEventInit extends EventInit {
    shiftKey?: boolean;
    ctrlKey?: boolean;
    altKey?: boolean;
    metaKey?: boolean;
  }
  interface ModifierState {
    readonly shiftKey: boolean;
    readonly ctrlKey: boolean;
    readonly altKey: boolean;
    readonly metaKey: boolean;
    getModifierState(key: 'Shift' | 'Control' | 'Alt' | 'Meta' | (string & {})): boolean;
  }

  export interface PointerEventInit extends ModifierEventInit {
    clientX?: number;
    clientY?: number;
    offsetX?: number;
    offsetY?: number;
    button?: number;
    buttons?: number;
    pointerId?: number;
    pointerType?: 'mouse' | 'pen' | 'touch' | '';
    pressure?: number;
    isPrimary?: boolean;
    relatedTarget?: UiNode | null;
  }
  export class PointerEvent extends Event implements ModifierState {
    constructor(type: string, init?: PointerEventInit);
    readonly shiftKey: boolean;
    readonly ctrlKey: boolean;
    readonly altKey: boolean;
    readonly metaKey: boolean;
    getModifierState(key: string): boolean;
    /** Relative to the view's top-left corner, in logical pixels. */
    readonly pageX: number;
    readonly pageY: number;
    /** Relative to the target's box, in logical pixels. */
    readonly locationX: number;
    readonly locationY: number;
    /** pageX and pageY, by their Web names. */
    readonly clientX: number;
    readonly clientY: number;
    readonly x: number;
    readonly y: number;
    /** locationX and locationY, by their Web names. */
    readonly offsetX: number;
    readonly offsetY: number;
    /** The button that changed: 0 primary, 1 middle, 2 secondary; -1 none. */
    readonly button: number;
    /** Buttons held: 1 primary, 2 secondary, 4 middle. */
    readonly buttons: number;
    readonly pointerId: number;
    readonly pointerType: 'mouse' | 'pen' | 'touch' | '';
    readonly pressure: number;
    readonly isPrimary: boolean;
    readonly relatedTarget: UiNode | null;
    readonly target: UiNode | null;
    readonly currentTarget: UiNode | null;
  }

  export interface WheelEventInit extends PointerEventInit {
    deltaX?: number;
    deltaY?: number;
    deltaMode?: 0 | 1 | 2;
  }
  export class WheelEvent extends PointerEvent {
    constructor(type: string, init?: WheelEventInit);
    /** Positive scrolls right. */
    readonly deltaX: number;
    /** Positive scrolls down. */
    readonly deltaY: number;
    readonly deltaZ: number;
    /** 0: pixels, 1: lines, 2: pages. */
    readonly deltaMode: 0 | 1 | 2;
    static readonly DOM_DELTA_PIXEL: 0;
    static readonly DOM_DELTA_LINE: 1;
    static readonly DOM_DELTA_PAGE: 2;
  }

  export interface KeyboardEventInit extends ModifierEventInit {
    key?: string;
    repeat?: boolean;
  }
  export class KeyboardEvent extends Event implements ModifierState {
    constructor(type: string, init?: KeyboardEventInit);
    readonly shiftKey: boolean;
    readonly ctrlKey: boolean;
    readonly altKey: boolean;
    readonly metaKey: boolean;
    getModifierState(key: string): boolean;
    /** The character, or a named key: 'Enter', 'ArrowLeft', 'Backspace'... */
    readonly key: string;
    readonly repeat: boolean;
    readonly target: UiNode | null;
    readonly currentTarget: UiNode | null;
  }

  export class FocusEvent extends Event {
    constructor(type: string, init?: EventInit & { relatedTarget?: UiNode | null });
    readonly relatedTarget: UiNode | null;
    readonly target: UiNode | null;
    readonly currentTarget: UiNode | null;
  }

  export class AccessibilityActionEvent extends Event {
    constructor(type: string, init?: EventInit & { actionName?: string; value?: number | string });
    /** 'activate', 'increment', 'setValue'..., or a custom action's name. */
    readonly actionName: AccessibilityActionName;
    /** setValue: the value asked for (a number, or an input's text). */
    readonly value: number | string | undefined;
    readonly target: UiNode | null;
    readonly currentTarget: UiNode | null;
  }

  export class InputEvent extends Event {
    constructor(type: string, init?: EventInit & { data?: string | null; inputType?: string });
    readonly data: string | null;
    readonly inputType: string;
    readonly target: UiNode | null;
    readonly currentTarget: UiNode | null;
  }
}
`;

export function renderUiDts(): string {
  return `${HEADER}${UI}`;
}
