/**
 * Renders the declaration of the runtime-provided `soundor:ui` module: the
 * plugin view's node tree, its flexbox style and its input events. The same
 * for every project.
 */

const HEADER = '// This file was generated by Soundor. Do not edit.\n\n';

const UI = `declare module 'soundor:ui' {
  /** Logical pixels, a percentage of the parent, or (where allowed) 'auto'. */
  export type Dimension = number | \`\${number}%\` | 'auto';
  export type Percentage = number | \`\${number}%\`;
  export type FlexAlign =
    | 'auto'
    | 'flex-start'
    | 'center'
    | 'flex-end'
    | 'stretch'
    | 'baseline'
    | 'space-between'
    | 'space-around'
    | 'space-evenly';

  /**
   * Flexbox layout as in React Native (column by default, no shrinking unless
   * asked) and text properties.
   */
  export interface Style {
    display?: 'flex' | 'none';
    position?: 'relative' | 'absolute' | 'static';
    flexDirection?: 'column' | 'column-reverse' | 'row' | 'row-reverse';
    flexWrap?: 'nowrap' | 'wrap' | 'wrap-reverse';
    justifyContent?:
      | 'flex-start'
      | 'center'
      | 'flex-end'
      | 'space-between'
      | 'space-around'
      | 'space-evenly';
    alignItems?: FlexAlign;
    alignSelf?: FlexAlign;
    alignContent?: FlexAlign;
    /** \`flex: n\` (n > 0) grows by n, shrinks, and starts from zero. */
    flex?: number;
    flexGrow?: number;
    flexShrink?: number;
    flexBasis?: Dimension;

    width?: Dimension;
    height?: Dimension;
    minWidth?: Percentage;
    minHeight?: Percentage;
    maxWidth?: Percentage;
    maxHeight?: Percentage;
    aspectRatio?: number;
    boxSizing?: 'border-box' | 'content-box';

    margin?: Dimension;
    marginHorizontal?: Dimension;
    marginVertical?: Dimension;
    marginTop?: Dimension;
    marginRight?: Dimension;
    marginBottom?: Dimension;
    marginLeft?: Dimension;
    padding?: Percentage;
    paddingHorizontal?: Percentage;
    paddingVertical?: Percentage;
    paddingTop?: Percentage;
    paddingRight?: Percentage;
    paddingBottom?: Percentage;
    paddingLeft?: Percentage;
    borderWidth?: number;
    borderHorizontalWidth?: number;
    borderVerticalWidth?: number;
    borderTopWidth?: number;
    borderRightWidth?: number;
    borderBottomWidth?: number;
    borderLeftWidth?: number;
    inset?: Dimension;
    top?: Dimension;
    right?: Dimension;
    bottom?: Dimension;
    left?: Dimension;
    gap?: number;
    rowGap?: number;
    columnGap?: number;

    overflow?: 'visible' | 'hidden' | 'scroll';
    /** 'box-none': not the node, but its children; 'box-only': the reverse. */
    pointerEvents?: 'auto' | 'none' | 'box-none' | 'box-only';

    fontFamily?: string;
    fontSize?: number;
    fontWeight?: number | 'normal' | 'bold';
    fontStyle?: 'normal' | 'italic';
    lineHeight?: number;
    letterSpacing?: number;
    textAlign?: 'auto' | 'left' | 'center' | 'right';
    /** Text nodes: at most this many lines (0: no limit). */
    numberOfLines?: number;
  }

  export interface LayoutRect {
    readonly x: number;
    readonly y: number;
    readonly width: number;
    readonly height: number;
  }

  export interface UiEventMap {
    pointerdown: PointerEvent;
    pointermove: PointerEvent;
    pointerup: PointerEvent;
    pointercancel: PointerEvent;
    pointerenter: PointerEvent;
    pointerleave: PointerEvent;
    click: PointerEvent;
    wheel: WheelEvent;
    keydown: KeyboardEvent;
    keyup: KeyboardEvent;
    beforeinput: InputEvent;
    focus: FocusEvent;
    blur: FocusEvent;
  }

  /**
   * A node of the view: a flexbox box ('view') or a run of text ('text').
   * Events capture and bubble along the tree as in the DOM.
   */
  export class UiNode extends EventTarget {
    private constructor();
    readonly type: 'view' | 'text';
    readonly parent: UiNode | null;
    readonly children: readonly UiNode[];
    readonly firstChild: UiNode | null;
    readonly lastChild: UiNode | null;
    readonly nextSibling: UiNode | null;
    readonly previousSibling: UiNode | null;
    /** Whether the node is in the view's tree. */
    readonly isConnected: boolean;
    /** Replaced as a whole on assignment. */
    style: Readonly<Style>;
    /** Text nodes only. */
    text: string;
    /** Whether the node takes focus when pressed or tabbed to. */
    focusable: boolean;
    readonly focused: boolean;
    focus(): void;
    blur(): void;
    appendChild<T extends UiNode>(child: T): T;
    insertBefore<T extends UiNode>(child: T, before: UiNode | null): T;
    removeChild<T extends UiNode>(child: T): T;
    remove(): void;
    contains(other: UiNode | null): boolean;
    /** The laid-out box, relative to the parent's. */
    readonly layout: LayoutRect;
    /** The laid-out box, relative to the view. */
    getBoundingClientRect(): LayoutRect;
    addEventListener<K extends keyof UiEventMap>(
      type: K,
      listener: (this: UiNode, event: UiEventMap[K]) => void,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject | null,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof UiEventMap>(
      type: K,
      listener: (this: UiNode, event: UiEventMap[K]) => void,
      options?: boolean | { capture?: boolean },
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject | null,
      options?: boolean | { capture?: boolean },
    ): void;
  }

  /** The view's root node; it always fills the view. */
  export const root: UiNode;
  export function createView(style?: Style): UiNode;
  export function createText(text?: string, style?: Style): UiNode;
  /** The node that has keyboard focus, if any. */
  export function focusedNode(): UiNode | null;
  /** The view's size in logical pixels, and device pixels per logical pixel. */
  export function viewSize(): { width: number; height: number; scale: number };

  interface ModifierEventInit extends EventInit {
    shiftKey?: boolean;
    ctrlKey?: boolean;
    altKey?: boolean;
    metaKey?: boolean;
  }
  interface ModifierState {
    readonly shiftKey: boolean;
    readonly ctrlKey: boolean;
    readonly altKey: boolean;
    readonly metaKey: boolean;
    getModifierState(key: 'Shift' | 'Control' | 'Alt' | 'Meta' | (string & {})): boolean;
  }

  export interface PointerEventInit extends ModifierEventInit {
    clientX?: number;
    clientY?: number;
    offsetX?: number;
    offsetY?: number;
    button?: number;
    buttons?: number;
    pointerId?: number;
    pointerType?: 'mouse' | 'pen' | 'touch' | '';
    pressure?: number;
    isPrimary?: boolean;
    relatedTarget?: UiNode | null;
  }
  export class PointerEvent extends Event implements ModifierState {
    constructor(type: string, init?: PointerEventInit);
    readonly shiftKey: boolean;
    readonly ctrlKey: boolean;
    readonly altKey: boolean;
    readonly metaKey: boolean;
    getModifierState(key: string): boolean;
    /** Relative to the view. */
    readonly clientX: number;
    readonly clientY: number;
    readonly x: number;
    readonly y: number;
    /** Relative to the target. */
    readonly offsetX: number;
    readonly offsetY: number;
    /** The button that changed: 0 primary, 1 middle, 2 secondary; -1 none. */
    readonly button: number;
    /** Buttons held: 1 primary, 2 secondary, 4 middle. */
    readonly buttons: number;
    readonly pointerId: number;
    readonly pointerType: 'mouse' | 'pen' | 'touch' | '';
    readonly pressure: number;
    readonly isPrimary: boolean;
    readonly relatedTarget: UiNode | null;
    readonly target: UiNode | null;
    readonly currentTarget: UiNode | null;
  }

  export interface WheelEventInit extends PointerEventInit {
    deltaX?: number;
    deltaY?: number;
    deltaMode?: 0 | 1 | 2;
  }
  export class WheelEvent extends PointerEvent {
    constructor(type: string, init?: WheelEventInit);
    /** Positive scrolls right. */
    readonly deltaX: number;
    /** Positive scrolls down. */
    readonly deltaY: number;
    readonly deltaZ: number;
    /** 0: pixels, 1: lines, 2: pages. */
    readonly deltaMode: 0 | 1 | 2;
    static readonly DOM_DELTA_PIXEL: 0;
    static readonly DOM_DELTA_LINE: 1;
    static readonly DOM_DELTA_PAGE: 2;
  }

  export interface KeyboardEventInit extends ModifierEventInit {
    key?: string;
    repeat?: boolean;
  }
  export class KeyboardEvent extends Event implements ModifierState {
    constructor(type: string, init?: KeyboardEventInit);
    readonly shiftKey: boolean;
    readonly ctrlKey: boolean;
    readonly altKey: boolean;
    readonly metaKey: boolean;
    getModifierState(key: string): boolean;
    /** The character, or a named key: 'Enter', 'ArrowLeft', 'Backspace'... */
    readonly key: string;
    readonly repeat: boolean;
    readonly target: UiNode | null;
    readonly currentTarget: UiNode | null;
  }

  export class FocusEvent extends Event {
    constructor(type: string, init?: EventInit & { relatedTarget?: UiNode | null });
    readonly relatedTarget: UiNode | null;
    readonly target: UiNode | null;
    readonly currentTarget: UiNode | null;
  }

  export class InputEvent extends Event {
    constructor(type: string, init?: EventInit & { data?: string | null; inputType?: string });
    readonly data: string | null;
    readonly inputType: string;
    readonly target: UiNode | null;
    readonly currentTarget: UiNode | null;
  }
}
`;

export function renderUiDts(): string {
  return `${HEADER}${UI}`;
}
