/**
 * The project data the Web host runs on: generated by the runtime's `gen`
 * into `.soundor/generated/runtimes/web/manifest.json` from soundor.config.
 * Everything else the host needs is generic and lives in this package.
 */

/** A declared parameter, in the shape `soundor:parameters` reports as `info`. */
export type WebParameterInfo =
  | {
      readonly id: string;
      readonly label: string;
      readonly type: 'float' | 'int';
      readonly min: number;
      readonly max: number;
      readonly default: number;
      readonly unit?: string;
    }
  | {
      readonly id: string;
      readonly label: string;
      readonly type: 'bool';
      readonly default: boolean;
    }
  | {
      readonly id: string;
      readonly label: string;
      readonly type: 'enum';
      readonly values: readonly string[];
      readonly default: string;
    };

/** The generated manifest. */
export interface WebManifest {
  /** The plugin's identity, from soundor.config. */
  readonly plugin: { readonly id: string; readonly name: string };
  /** Every declared parameter, in declaration order. */
  readonly parameters: readonly WebParameterInfo[];
}
