// This file was generated by Soundor. Do not edit.

import {
  defineHandle,
  type WebNativeHandle,
} from '@soundor/web-runtime/client';

export type Curve = 'linear' | 'exponential';

/** An opaque reference to a Preset: `Preset.wrap(value)` makes one, `Preset.unwrap(handle)` gets the value back. */
export type Preset = WebNativeHandle<'Preset'>;
export const Preset = defineHandle('Preset');

export interface Analysis {
  rms: number;
  peaks: number[];
}

/**
 * The plugin's native API (soundor:native), as runtimes/web/src/native.ts
 * implements it for the Web. A method added to soundor.config is missing
 * here until it is implemented.
 */
export interface WebNativeApi {
  analyze(samples: Float32Array): Analysis;
  echo(data: Uint8Array): ArrayBuffer;
  fail(): void;
  failLater(): Promise<void>;
  invert(on: boolean): boolean;
  loadPreset(path: string): Promise<Preset>;
  presetName(preset: Preset): string;
  scale(values: readonly number[], factor: number): number[];
  setCurve(curve: Curve): void;
}
