// This file was generated by Soundor. Do not edit.

declare module 'soundor:parameters' {
  /** Metadata of a parameter, as declared in soundor.config. */
  export type ParameterInfo =
    | {
        readonly id: string;
        readonly label: string;
        readonly type: 'float' | 'int';
        readonly min: number;
        readonly max: number;
        readonly default: number;
        readonly unit?: string;
      }
    | {
        readonly id: string;
        readonly label: string;
        readonly type: 'bool';
        readonly default: boolean;
      }
    | {
        readonly id: string;
        readonly label: string;
        readonly type: 'enum';
        readonly values: readonly string[];
        readonly default: string;
      };

  /**
   * A plugin parameter, shared with the DSP and the host. Values are in plain
   * units: numbers within [min, max], booleans, or one of an enum's values.
   */
  export interface Parameter<Value, Info extends ParameterInfo = ParameterInfo> {
    readonly id: Info['id'];
    readonly info: Info;
    /** The current value. */
    get(): Value;
    /** Sets the value (numbers are clamped to the range, ints rounded) and notifies the host. */
    set(value: Value): void;
    /**
     * Calls `listener` with the new value after every change, from any source:
     * the UI, host automation, or a preset. Returns a function that unsubscribes.
     */
    subscribe(listener: (value: Value) => void): () => void;
    /** Starts a user interaction (e.g. a drag); the host records the changes until endGesture() as one gesture. */
    beginGesture(): void;
    /** Ends the interaction started with beginGesture(). */
    endGesture(): void;
  }

  /** Every parameter declared in soundor.config, by id. */
  export const parameters: {
    readonly bypass: Parameter<boolean, { readonly id: "bypass"; readonly label: "Bypass"; readonly type: "bool"; readonly default: false }>;
    readonly gain: Parameter<number, { readonly id: "gain"; readonly label: "Gain"; readonly type: "float"; readonly min: 0; readonly max: 1; readonly default: 0.5; readonly unit: "dB" }>;
    readonly mode: Parameter<"clean" | "warm" | "hot", { readonly id: "mode"; readonly label: "Mode"; readonly type: "enum"; readonly values: readonly ["clean", "warm", "hot"]; readonly default: "warm" }>;
    readonly steps: Parameter<number, { readonly id: "steps"; readonly label: "Steps"; readonly type: "int"; readonly min: 1; readonly max: 8; readonly default: 4 }>;
  };
}
