// This file was generated by Soundor. Do not edit.

declare module 'soundor:host' {
  export interface Transport {
    readonly playing: boolean;
    readonly recording: boolean;
    readonly looping: boolean;
    readonly bpm: number;
    readonly timeSignature: { readonly numerator: number; readonly denominator: number };
    /** Musical position in quarter notes, and where its bar starts. */
    readonly ppqPosition: number;
    readonly barStartPpq: number;
    readonly timeInSeconds: number;
    readonly timeInSamples: number;
  }

  export interface HostSnapshot {
    readonly sampleRate: number;
    readonly blockSize: number;
    /** The host's name, when the plugin can tell (e.g. "Reaper"). */
    readonly hostName: string;
    /** null until the host reports a transport. */
    readonly transport: Transport | null;
  }

  /** This plugin's identity, from soundor.config. */
  export const plugin: { readonly id: "com.example.fixture"; readonly name: "Fixture" };

  /** The current host state. */
  export function snapshot(): HostSnapshot;

  /** Calls `listener` whenever the host state changes (every frame while playing). Returns an unsubscribe function. */
  export function subscribe(listener: (snapshot: HostSnapshot) => void): () => void;
}

declare module 'soundor:storage' {
  /** Persistent key/value storage private to this plugin. Values are JSON data. */
  export const storage: {
    get<T = unknown>(key: string): Promise<T | undefined>;
    set(key: string, value: unknown): Promise<void>;
    delete(key: string): Promise<void>;
    keys(): Promise<string[]>;
    clear(): Promise<void>;
  };
}

declare module 'soundor:fs' {
  /**
   * File access confined to this plugin's data directory. Paths are relative
   * and '/'-separated ('presets/warm.json'); they cannot leave the directory.
   */
  export interface DirectoryEntry {
    readonly name: string;
    readonly kind: 'file' | 'directory';
  }

  export interface FileStat {
    readonly kind: 'file' | 'directory';
    readonly size: number;
    /** Last modification, in milliseconds since the Unix epoch. */
    readonly modified: number;
  }

  export function readBytes(path: string): Promise<Uint8Array>;
  export function readText(path: string): Promise<string>;
  /** Replaces the file atomically, creating missing parent directories. */
  export function writeBytes(path: string, data: ArrayBuffer | ArrayBufferView): Promise<void>;
  export function writeText(path: string, text: string): Promise<void>;
  export function readDir(path?: string): Promise<DirectoryEntry[]>;
  export function mkdir(path: string, options?: { recursive?: boolean }): Promise<void>;
  export function remove(path: string, options?: { recursive?: boolean }): Promise<void>;
  export function stat(path: string): Promise<FileStat | null>;
  export function exists(path: string): Promise<boolean>;
}
