// This file was generated by Soundor. Do not edit.

declare module 'soundor:native' {
  export type Curve = "linear" | "exponential";

  /** An opaque reference to a native Preset. Only native methods can create one. */
  export interface Preset {
    readonly __soundorHandle: 'Preset';
  }

  export interface Analysis {
    rms: number;
    peaks: number[];
  }

  export function analyze(samples: Float32Array): Analysis;

  export function echo(data: Uint8Array): ArrayBuffer;

  export function fail(): void;

  export function failLater(): Promise<void>;

  export function invert(on: boolean): boolean;

  export function loadPreset(path: string): Promise<Preset>;

  export function presetName(preset: Preset): string;

  export function scale(values: readonly number[], factor: number): number[];

  export function setCurve(curve: Curve): void;
}
