"""Turns gn's view of an ANGLE build (`gn gen --ide=json`) into a CMake file
that cmake/angle/CMakeLists.txt compiles with Soundor's own toolchain.

  targets.py <project.json> <source root> <out.cmake> <target>...

gn decides what ANGLE is made of for a platform and configuration (sources,
defines, include paths, link libraries); Chromium's toolchain, which would
compile it with a Clang of its own, is never used. Only flags that change what
the code means are kept (instruction sets, aliasing, exceptions, RTTI, ARC);
warnings, sanitizers and code generation are Soundor's choice.

The output calls angle_target() once per gn target that compiles something,
and sets ANGLE_GENERATED (files gn actions make, relative to the gn build
directory), ANGLE_LIBS and ANGLE_FRAMEWORKS (what the result links against).
"""

import json
import os
import re
import sys

KEEP_FLAG = re.compile(
    r'^(-[DU]\S+|/[DU]\S+'
    r'|-m(sse|ssse|avx|pclmul|aes|bmi|f16c|fma|popcnt|crc|neon)[0-9a-z.]*'
    r'|-f(no-)?(strict-aliasing|exceptions|rtti|objc-arc)'
    r'|/arch:\S+|/GR-?)$'
)
# Chromium's own configuration, not ANGLE's.
DROP_DEFINE = re.compile(
    r'^(USE_(AURA|GLIB|OZONE|UDEV)\b|_LIBCPP_|_GLIBCXX_|CR_|_FORTIFY_SOURCE|COMPONENT_BUILD|NDEBUG|NVALGRIND'
    r'|DYNAMIC_ANNOTATIONS_ENABLED|_DEBUG|__STDC_|__DATE__|__TIME__|__TIMESTAMP__)'
)
COMPILED = ('.c', '.cc', '.cpp', '.cxx', '.m', '.mm')
SKIPPED_DEPS = ('//buildtools/third_party/libc++', '//buildtools/third_party/libc++abi')


def main():
    project, root, out, roots = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4:]
    targets = json.load(open(project, encoding='utf-8'))['targets']
    root = root.replace('\\', '/').rstrip('/')

    def path(label):
        if not label.startswith('//'):
            return label.replace('\\', '/')
        return (root + '/' + label[2:]).rstrip('/')

    # Every target the roots depend on, dependencies first.
    order, seen = [], set()

    def walk(name):
        if name in seen:
            return
        seen.add(name)
        for dep in targets[name].get('deps', []):
            if not dep.startswith(SKIPPED_DEPS):
                walk(dep)
        order.append(name)

    for name in roots:
        walk(name)

    def cmake_list(values):
        return ' '.join('"' + v.replace('\\', '/').replace('"', '\\"') + '"' for v in values)

    calls, generated, libs, frameworks = [], [], [], []
    for name in order:
        target = targets[name]
        for lib in target.get('libs', []):
            # Chromium's Clang runtime: the compiler that links the plugin has its own.
            if '/' not in lib and '\\' not in lib and lib not in libs:
                libs.append(lib)
        for framework in target.get('frameworks', []):
            if framework not in frameworks:
                frameworks.append(framework)
        if target['type'] in ('action', 'action_foreach', 'copy'):
            build_dir = os.path.dirname(project).replace('\\', '/')
            for output in target.get('outputs', []):
                generated.append(os.path.relpath(path(output), build_dir).replace('\\', '/'))
            continue
        sources = [path(s) for s in target.get('sources', []) if s.endswith(COMPILED)]
        if not sources:
            continue
        defines = [d for d in target.get('defines', []) if not DROP_DEFINE.match(d)]
        # A function-like macro cannot be a CMake compile definition.
        macros = ['-D' + d for d in defines if '(' in d.split('=')[0]]
        defines = [d for d in defines if '(' not in d.split('=')[0]]
        includes = [path(i) for i in target.get('include_dirs', [])]
        flags = []
        for key in ('cflags', 'cflags_c', 'cflags_cc', 'cflags_objc', 'cflags_objcc'):
            for flag in target.get(key, []):
                if KEEP_FLAG.match(flag) and not DROP_DEFINE.match(flag[2:]) and flag not in flags:
                    flags.append(flag)
        ident = re.sub(r'[^A-Za-z0-9_]', '_', name.lstrip('/'))
        calls.append(
            f'angle_target({ident}\n'
            f'  SOURCES {cmake_list(sources)}\n'
            f'  DEFINES {cmake_list(defines)}\n'
            f'  INCLUDES {cmake_list(includes)}\n'
            f'  FLAGS {cmake_list(flags + macros)})\n'
        )

    with open(out, 'w', encoding='utf-8') as file:
        file.write('# Generated by targets.py from gn\'s project.json.\n')
        file.writelines(calls)
        file.write(f'set(ANGLE_GENERATED {cmake_list(generated)})\n')
        file.write(f'set(ANGLE_LIBS {cmake_list(libs)})\n')
        file.write(f'set(ANGLE_FRAMEWORKS {cmake_list(frameworks)})\n')


if __name__ == '__main__':
    main()
